/**
 * Curated exercise catalog: 570 exercises across 13 muscle groups, each with a
 * demonstration video link where one exists.
 *
 * GENERATED from the gym's exercise spreadsheet and then corrected - do not
 * re-sort by hand. The source sheet only labeled the first row of each block,
 * and several blocks were mis-grouped, so the groups below are NOT the sheet's
 * raw labels. The corrections that were applied:
 *   - "Quads" (160 rows) was really Quads + Hamstrings + Calves
 *   - "Upper Traps" (36 rows) was really Traps (shrugs) + Rear Delts
 *   - "Lateral Delts" is shown as Shoulders (it held presses and raises too)
 *   - "Glutes (Abduction)" is folded into Glutes; its trailing ~50 rows were an
 *     unsorted mix, re-assigned one by one
 *   - one Skullcrusher sitting among the Biceps moved to Triceps
 *   - exact-name duplicates removed; one entry whose "video" was a text note
 *     rather than a link now has no video
 */

export const MUSCLE_GROUPS = [
  "Chest",
  "Shoulders",
  "Rear Delts",
  "Traps",
  "Back (Horizontal Pull)",
  "Back (Vertical Pull)",
  "Biceps",
  "Triceps",
  "Quads",
  "Hamstrings",
  "Glutes",
  "Calves",
  "Core",
] as const;

export type MuscleGroup = (typeof MUSCLE_GROUPS)[number];

export interface CatalogExercise {
  /** Stable slug, e.g. "chest-push-up". */
  id: string;
  muscleGroup: MuscleGroup;
  name: string;
  /** Link to a demonstration video; null when none is known. */
  videoUrl: string | null;
}

export const EXERCISE_CATALOG: readonly CatalogExercise[] = [
  { id: "chest-15-degree-incline-db-bench-press", muscleGroup: "Chest", name: "15 Degree Incline DB Bench Press", videoUrl: "https://www.youtube.com/watch?v=UtaYxmL9-Yo" },
  { id: "chest-alternating-cable-bench-press", muscleGroup: "Chest", name: "Alternating Cable Bench Press", videoUrl: "https://www.youtube.com/watch?v=Tz00gVLwZeY" },
  { id: "chest-alternating-db-bench-press-bottom-up", muscleGroup: "Chest", name: "Alternating DB Bench Press (Bottom-up)", videoUrl: "https://www.youtube.com/watch?v=08Gc_YdvSnI" },
  { id: "chest-alternating-db-bench-press-top-down", muscleGroup: "Chest", name: "Alternating DB Bench Press (Top-Down)", videoUrl: "https://www.youtube.com/watch?v=klOzQZ0k9io" },
  { id: "chest-alternating-low-to-high-cable-fly", muscleGroup: "Chest", name: "Alternating Low-to-High Cable Fly", videoUrl: "https://youtu.be/eVr8qMXbaXU" },
  { id: "chest-archer-push-up", muscleGroup: "Chest", name: "Archer Push-up", videoUrl: "https://www.youtube.com/watch?v=25t7UBYCMbE" },
  { id: "chest-band-chest-fly", muscleGroup: "Chest", name: "Band Chest Fly", videoUrl: "https://youtu.be/1076zKHV7AM?t=33" },
  { id: "chest-band-chest-press", muscleGroup: "Chest", name: "Band Chest Press", videoUrl: "https://youtu.be/3rX4hA8aPgQ?t=16" },
  { id: "chest-barbell-floor-press", muscleGroup: "Chest", name: "Barbell Floor Press", videoUrl: "https://youtu.be/9vYCwtHkWgI" },
  { id: "chest-bayesian-fly", muscleGroup: "Chest", name: "Bayesian Fly", videoUrl: "https://www.youtube.com/watch?v=wuv-km9eHfU" },
  { id: "chest-belt-weighted-push-up", muscleGroup: "Chest", name: "Belt Weighted Push-up", videoUrl: "https://www.youtube.com/watch?v=4yiVqLAauRg" },
  { id: "chest-bench-dips", muscleGroup: "Chest", name: "Bench Dips", videoUrl: "https://youtu.be/c3ZGl4pAwZ4?t=32" },
  { id: "chest-bench-press", muscleGroup: "Chest", name: "Bench Press", videoUrl: "https://www.youtube.com/watch?v=UKweKjaw5rA" },
  { id: "chest-cable-bench-press-dual-cable", muscleGroup: "Chest", name: "Cable Bench Press (Dual Cable)", videoUrl: "https://www.youtube.com/watch?v=Is8Htqk2HPg" },
  { id: "chest-cable-bench-press-straight-bar", muscleGroup: "Chest", name: "Cable Bench Press (Straight Bar)", videoUrl: "https://www.youtube.com/watch?v=NhD3h6RG2TA" },
  { id: "chest-cable-fly-high-to-low", muscleGroup: "Chest", name: "Cable Fly (High-to-Low)", videoUrl: "https://youtu.be/Rwz69lvgJys?t=7" },
  { id: "chest-cable-fly-low-to-high", muscleGroup: "Chest", name: "Cable Fly (Low-to-High)", videoUrl: "https://www.youtube.com/watch?v=jBDRY89Xt78" },
  { id: "chest-cable-press-half-kneeling", muscleGroup: "Chest", name: "Cable Press (Half-Kneeling)", videoUrl: "https://www.youtube.com/watch?v=cLkZQMcJ-Mo" },
  { id: "chest-chest-dips", muscleGroup: "Chest", name: "Chest Dips", videoUrl: "https://youtu.be/yN6Q1UI_xkE?si=L5tcxRNwvfSpwbGZ&t=203" },
  { id: "chest-close-grip-bench-press", muscleGroup: "Chest", name: "Close Grip Bench Press", videoUrl: "https://youtu.be/nEF0bv2FW94?t=29" },
  { id: "chest-convergent-machine-chest-press", muscleGroup: "Chest", name: "Convergent Machine Chest Press", videoUrl: "https://www.youtube.com/watch?v=vnd-GBtTMLI" },
  { id: "chest-db-bench-press", muscleGroup: "Chest", name: "DB Bench Press", videoUrl: "https://www.youtube.com/watch?v=JJ2YrIF4GCY" },
  { id: "chest-db-floor-press", muscleGroup: "Chest", name: "DB Floor Press", videoUrl: "https://youtu.be/uUGDRwge4F8?t=20" },
  { id: "chest-db-fly", muscleGroup: "Chest", name: "DB Fly", videoUrl: "https://www.youtube.com/watch?v=JFm8KbhjibM" },
  { id: "chest-db-fly-w-foam-roller", muscleGroup: "Chest", name: "DB Fly w/Foam Roller", videoUrl: "https://youtu.be/UL2-Gqv-YG4?t=2" },
  { id: "chest-db-press-neutral-to-pronate", muscleGroup: "Chest", name: "DB Press Neutral to Pronate", videoUrl: "https://www.youtube.com/watch?v=a4PyHENXfHg" },
  { id: "chest-decline-alternating-db-bench-press", muscleGroup: "Chest", name: "Decline Alternating DB Bench Press", videoUrl: "https://youtu.be/OaeVMH03Wg4?t=8" },
  { id: "chest-decline-bench-press", muscleGroup: "Chest", name: "Decline Bench Press", videoUrl: "https://www.youtube.com/watch?v=m-tjofjekBM" },
  { id: "chest-decline-db-fly", muscleGroup: "Chest", name: "Decline DB Fly", videoUrl: "https://youtu.be/IMALXhhHRKM?t=29" },
  { id: "chest-deficit-push-up", muscleGroup: "Chest", name: "Deficit Push-up", videoUrl: "https://www.youtube.com/shorts/xE5y-QW9Yts" },
  { id: "chest-deficit-push-up-w-bands", muscleGroup: "Chest", name: "Deficit Push-up w/ Bands", videoUrl: "https://www.youtube.com/watch?v=p8thIwCgvCk&feature=youtu.be" },
  { id: "chest-deficit-push-up-w-feet-elevated", muscleGroup: "Chest", name: "Deficit Push-up w/Feet Elevated", videoUrl: "https://www.youtube.com/shorts/ia69UPuLQyo" },
  { id: "chest-high-to-low-cable-press", muscleGroup: "Chest", name: "High-to-Low Cable Press", videoUrl: "https://www.youtube.com/watch?v=6p4riimvJa0" },
  { id: "chest-hooklying-alternating-chest-press", muscleGroup: "Chest", name: "Hooklying Alternating Chest Press", videoUrl: "https://www.youtube.com/watch?v=9Tz0YcIUd2U" },
  { id: "chest-incline-alternating-db-bench-press-bottom-up", muscleGroup: "Chest", name: "Incline Alternating DB Bench Press (Bottom-up)", videoUrl: "https://www.youtube.com/watch?v=PPez5mzg5Zs" },
  { id: "chest-incline-bench-press", muscleGroup: "Chest", name: "Incline Bench Press", videoUrl: "https://www.youtube.com/watch?v=TZl0ImOVsF8" },
  { id: "chest-incline-db-bench-press", muscleGroup: "Chest", name: "Incline DB Bench Press", videoUrl: "https://www.youtube.com/watch?v=vc9UZ97Q4PM" },
  { id: "chest-incline-db-fly", muscleGroup: "Chest", name: "Incline DB Fly", videoUrl: "https://youtu.be/vE9KK77nddw?t=35s" },
  { id: "chest-incline-db-fly-neutral-to-pronated", muscleGroup: "Chest", name: "Incline DB Fly - Neutral to Pronated", videoUrl: "https://www.youtube.com/watch?v=AExff_3CS20" },
  { id: "chest-incline-db-press-neutral-to-pronate", muscleGroup: "Chest", name: "Incline DB Press Neutral to Pronate", videoUrl: "https://www.youtube.com/watch?v=R-WKA4veCgA" },
  { id: "chest-incline-push-up", muscleGroup: "Chest", name: "Incline Push-up", videoUrl: "https://www.youtube.com/watch?v=tFA8Qc0x65M" },
  { id: "chest-incline-push-up-w-bands", muscleGroup: "Chest", name: "Incline Push-up w/Bands", videoUrl: "https://www.youtube.com/watch?v=59clnPYGTeY" },
  { id: "chest-machine-chest-fly", muscleGroup: "Chest", name: "Machine Chest Fly", videoUrl: "https://youtu.be/22Q3bmNZk0Y?t=51" },
  { id: "chest-machine-chest-press-hammer", muscleGroup: "Chest", name: "Machine Chest Press (Hammer)", videoUrl: "https://youtu.be/gEzDvB1T1yA?t=27s" },
  { id: "chest-offset-push-up", muscleGroup: "Chest", name: "Offset Push-up", videoUrl: "https://www.youtube.com/watch?v=x1M0u2ufSOM" },
  { id: "chest-one-arm-band-press-high-to-low", muscleGroup: "Chest", name: "One-Arm Band Press (High-to-Low)", videoUrl: "https://www.youtube.com/watch?v=Wl5ZkGsng2A" },
  { id: "chest-one-arm-cable-bench-press", muscleGroup: "Chest", name: "One-Arm Cable Bench Press", videoUrl: "https://www.youtube.com/watch?v=h6bMqaBgJ-M" },
  { id: "chest-one-arm-cable-fly", muscleGroup: "Chest", name: "One-Arm Cable Fly", videoUrl: "https://youtu.be/vGGOR4DPDt0?t=13" },
  { id: "chest-one-arm-cable-fly-high-to-low", muscleGroup: "Chest", name: "One-Arm Cable Fly (High-to-Low)", videoUrl: "https://www.youtube.com/watch?v=iSwmOJ09-0A" },
  { id: "chest-one-arm-cable-fly-low-to-high", muscleGroup: "Chest", name: "One-Arm Cable Fly (Low-to-High)", videoUrl: "https://www.youtube.com/watch?v=FJfDGl1Z_mk" },
  { id: "chest-one-arm-clavicular-pec-cable-press", muscleGroup: "Chest", name: "One-Arm Clavicular Pec Cable Press", videoUrl: "https://www.youtube.com/watch?v=Lo6R9rllS78" },
  { id: "chest-one-arm-cross-body-cable-press", muscleGroup: "Chest", name: "One-Arm Cross Body Cable Press", videoUrl: "https://www.youtube.com/shorts/Zp2VNnWN34w" },
  { id: "chest-one-arm-db-bench-press", muscleGroup: "Chest", name: "One-Arm DB Bench Press", videoUrl: "https://www.youtube.com/watch?v=X8zXg41yziI" },
  { id: "chest-one-arm-front-foot-elevated-cable-press-high-to-low", muscleGroup: "Chest", name: "One-Arm Front Foot Elevated Cable Press (High-to-Low)", videoUrl: "https://www.youtube.com/watch?v=0Q69WrE0YpQ" },
  { id: "chest-one-arm-bayesian-fly", muscleGroup: "Chest", name: "One-arm Bayesian Fly", videoUrl: "https://www.youtube.com/watch?v=l-C45i-QUg8" },
  { id: "chest-push-up", muscleGroup: "Chest", name: "Push-up", videoUrl: "https://youtu.be/JyCG_5l3XLk?si=ikp4Ta5F_1cjE_Ac&t=14" },
  { id: "chest-push-up-w-bands", muscleGroup: "Chest", name: "Push-up w/ Bands", videoUrl: "https://www.youtube.com/watch?v=Bik5ewx6iFM&feature=youtu.be" },
  { id: "chest-reverse-push-up", muscleGroup: "Chest", name: "Reverse Push-up", videoUrl: "https://youtu.be/-UZSxxO3XI8" },
  { id: "chest-ring-fly", muscleGroup: "Chest", name: "Ring Fly", videoUrl: "https://www.youtube.com/watch?v=1kqvd7yyIvs&feature=youtu.be" },
  { id: "chest-seated-cable-fly", muscleGroup: "Chest", name: "Seated Cable Fly", videoUrl: "https://www.youtube.com/watch?v=kMmV0thhwnA" },
  { id: "chest-smith-machine-bench-press", muscleGroup: "Chest", name: "Smith Machine Bench Press", videoUrl: "https://www.youtube.com/watch?v=Aw7C1PADw84" },
  { id: "chest-staggered-stance-cable-fly-high-to-low", muscleGroup: "Chest", name: "Staggered Stance Cable Fly (High-to-Low)", videoUrl: "https://youtu.be/KwvJEXts2lg?t=141" },
  { id: "chest-supinated-db-fly", muscleGroup: "Chest", name: "Supinated DB Fly", videoUrl: "https://www.youtube.com/watch?v=lPH7l4Ul2HI" },
  { id: "chest-suspended-push-up", muscleGroup: "Chest", name: "Suspended Push-up", videoUrl: "https://youtu.be/jk4MGqOmjn4?t=2" },
  { id: "chest-trx-fly", muscleGroup: "Chest", name: "TRX Fly", videoUrl: "https://www.youtube.com/watch?v=A0ptzi0tfM4" },
  { id: "shoulders-anterior-delt-cable-raise-to-ear", muscleGroup: "Shoulders", name: "Anterior Delt Cable Raise to Ear", videoUrl: "https://www.youtube.com/watch?v=AewELFT0TWI" },
  { id: "shoulders-anterior-delt-high-incline-db-press-elbows-in-front", muscleGroup: "Shoulders", name: "Anterior Delt High Incline DB Press (Elbows In Front)", videoUrl: "https://www.youtube.com/watch?v=FF7VwUuIkec" },
  { id: "shoulders-arnold-press", muscleGroup: "Shoulders", name: "Arnold Press", videoUrl: "https://www.youtube.com/watch?v=aBRJR3s3NTI" },
  { id: "shoulders-band-lateral-raise", muscleGroup: "Shoulders", name: "Band Lateral Raise", videoUrl: "https://youtu.be/QqyKKd3dXGk?t=7" },
  { id: "shoulders-band-one-arm-lateral-raise", muscleGroup: "Shoulders", name: "Band One-arm Lateral Raise", videoUrl: "https://www.youtube.com/watch?v=yfNg5sFndbw" },
  { id: "shoulders-band-overhead-press", muscleGroup: "Shoulders", name: "Band Overhead Press", videoUrl: "https://youtu.be/Zli1UXH9ZeE?t=2" },
  { id: "shoulders-band-upright-row", muscleGroup: "Shoulders", name: "Band Upright Row", videoUrl: "https://youtu.be/bfzl23IIOi8?t=33s" },
  { id: "shoulders-barbell-push-press", muscleGroup: "Shoulders", name: "Barbell Push Press", videoUrl: "https://www.youtube.com/watch?v=iaBVSJm78ko" },
  { id: "shoulders-behind-back-cable-lateral-raise-scaption", muscleGroup: "Shoulders", name: "Behind Back Cable Lateral Raise (Scaption)", videoUrl: "https://www.youtube.com/shorts/2Lcfu-Qd59g" },
  { id: "shoulders-bodyweight-lateral-raise", muscleGroup: "Shoulders", name: "Bodyweight Lateral Raise", videoUrl: "https://www.exrx.net/WeightExercises/Obliques/BWAngledSideBridge" },
  { id: "shoulders-butterfly-lateral-raise", muscleGroup: "Shoulders", name: "Butterfly Lateral Raise", videoUrl: "https://www.youtube.com/watch?v=vdHmEFu2XVk&feature=youtu.be" },
  { id: "shoulders-cable-front-raise", muscleGroup: "Shoulders", name: "Cable Front Raise", videoUrl: "https://www.youtube.com/watch?v=9iIfZJKTa1A" },
  { id: "shoulders-cable-landmine-press-half-kneeling", muscleGroup: "Shoulders", name: "Cable Landmine Press Half-Kneeling", videoUrl: "https://www.youtube.com/watch?v=YaNlV2CSe1U" },
  { id: "shoulders-cable-upright-row", muscleGroup: "Shoulders", name: "Cable Upright Row", videoUrl: "https://youtu.be/zXFM7jD7WB4" },
  { id: "shoulders-crossover-cable-lateral-raise", muscleGroup: "Shoulders", name: "Crossover Cable Lateral Raise", videoUrl: "https://www.youtube.com/watch?v=wKgCc5UQjoU" },
  { id: "shoulders-db-lateral-raise", muscleGroup: "Shoulders", name: "DB Lateral Raise", videoUrl: "https://www.youtube.com/watch?v=geenhiHju-o" },
  { id: "shoulders-front-raise", muscleGroup: "Shoulders", name: "Front Raise", videoUrl: "https://www.youtube.com/watch?v=Q7G67jq9rjM" },
  { id: "shoulders-front-raise-neutral-alternating", muscleGroup: "Shoulders", name: "Front Raise (Neutral/Alternating)", videoUrl: "https://youtu.be/-t7fuZ0KhDA?t=12" },
  { id: "shoulders-half-kneeling-one-arm-cable-overhead-press", muscleGroup: "Shoulders", name: "Half-Kneeling One-Arm Cable Overhead Press", videoUrl: "https://www.youtube.com/watch?v=6D-O-DfcfmY" },
  { id: "shoulders-half-kneeling-one-arm-overhead-press", muscleGroup: "Shoulders", name: "Half-Kneeling One-Arm Overhead Press", videoUrl: "https://www.youtube.com/watch?v=FLbz81jkVIM" },
  { id: "shoulders-handstand-push-ups", muscleGroup: "Shoulders", name: "Handstand Push-ups", videoUrl: "https://www.youtube.com/watch?v=0wDEO6shVjc" },
  { id: "shoulders-incline-arnold-press", muscleGroup: "Shoulders", name: "Incline Arnold Press", videoUrl: "https://www.youtube.com/watch?v=hDboAOhrckY" },
  { id: "shoulders-kb-snatch", muscleGroup: "Shoulders", name: "KB Snatch", videoUrl: "https://youtu.be/6MGUllzX_0g?si=OUU_XyR0_33uo8WW&t=100" },
  { id: "shoulders-l-handstand-push-up", muscleGroup: "Shoulders", name: "L-Handstand Push-up", videoUrl: "https://www.youtube.com/watch?v=ytczHUp_33c" },
  { id: "shoulders-l-seated-one-arm-overhead-press", muscleGroup: "Shoulders", name: "L-Seated One-Arm Overhead Press", videoUrl: "https://www.youtube.com/watch?v=gcHAKa0E-KI" },
  { id: "shoulders-l-seated-overhead-press", muscleGroup: "Shoulders", name: "L-Seated Overhead Press", videoUrl: "https://www.youtube.com/watch?v=4pbdO9mBE5M" },
  { id: "shoulders-landmine-press-half-kneeling", muscleGroup: "Shoulders", name: "Landmine Press Half-Kneeling", videoUrl: "https://www.youtube.com/watch?v=ORoOn93dnh4" },
  { id: "shoulders-landmine-press-tall-kneeling", muscleGroup: "Shoulders", name: "Landmine Press Tall Kneeling", videoUrl: "https://youtu.be/1G-_FTEkoNw?t=10" },
  { id: "shoulders-lateral-raise-w-bottle", muscleGroup: "Shoulders", name: "Lateral Raise w/ bottle", videoUrl: "https://www.youtube.com/watch?v=dr8ItbfGAVE" },
  { id: "shoulders-leaning-cable-lateral-raise", muscleGroup: "Shoulders", name: "Leaning Cable Lateral Raise", videoUrl: "https://www.youtube.com/shorts/WUlQ_NZI-CA" },
  { id: "shoulders-long-seated-landmine-press", muscleGroup: "Shoulders", name: "Long-Seated Landmine Press", videoUrl: "https://www.youtube.com/watch?v=_ZWBNa4OHSw" },
  { id: "shoulders-machine-shoulder-press", muscleGroup: "Shoulders", name: "Machine Shoulder Press", videoUrl: "https://www.youtube.com/watch?v=WvLMauqrnK8" },
  { id: "shoulders-modified-upright-row", muscleGroup: "Shoulders", name: "Modified Upright Row", videoUrl: "https://www.youtube.com/watch?v=LT0UjVVcB1A" },
  { id: "shoulders-one-arm-behind-back-cable-lateral-raise", muscleGroup: "Shoulders", name: "One-Arm Behind Back Cable Lateral Raise", videoUrl: "https://www.youtube.com/shorts/UYEFbFUOcc8" },
  { id: "shoulders-one-arm-cable-lateral-raise", muscleGroup: "Shoulders", name: "One-Arm Cable Lateral Raise", videoUrl: "https://www.youtube.com/watch?v=aFJa60WJ4aI&feature=youtu.be" },
  { id: "shoulders-one-arm-kb-overhead-press", muscleGroup: "Shoulders", name: "One-Arm KB Overhead Press", videoUrl: "https://youtu.be/WTmR-Qr32dg?si=k7O-hiMbwoIF9Kl-&t=30" },
  { id: "shoulders-one-arm-landmine-press-tall-kneeling", muscleGroup: "Shoulders", name: "One-Arm Landmine Press Tall Kneeling", videoUrl: "https://www.youtube.com/watch?v=5aBlEtgiL44" },
  { id: "shoulders-one-arm-standing-cable-overhead-press", muscleGroup: "Shoulders", name: "One-Arm Standing Cable Overhead Press", videoUrl: "https://youtu.be/pDdOThPUJsk?t=4" },
  { id: "shoulders-pike-push-ups", muscleGroup: "Shoulders", name: "Pike Push-ups", videoUrl: "https://www.youtube.com/watch?v=XckEEwa1BPI" },
  { id: "shoulders-prone-chest-supported-lateral-raise", muscleGroup: "Shoulders", name: "Prone Chest-Supported Lateral Raise", videoUrl: "https://www.youtube.com/watch?v=P7x4BfMa1JY" },
  { id: "shoulders-prone-incline-db-y-raise", muscleGroup: "Shoulders", name: "Prone Incline DB Y-Raise", videoUrl: "https://youtu.be/lXp16YozXgk?t=106" },
  { id: "shoulders-scaption-lateral-raises", muscleGroup: "Shoulders", name: "Scaption Lateral Raises", videoUrl: "https://youtu.be/pDtt6b9NUSU?t=34" },
  { id: "shoulders-scrape-rack-l-seated-shoulder-press", muscleGroup: "Shoulders", name: "Scrape Rack L-Seated Shoulder Press", videoUrl: "https://www.youtube.com/watch?v=o0kpHTQ2nN4" },
  { id: "shoulders-scrape-rack-shoulder-press", muscleGroup: "Shoulders", name: "Scrape Rack Shoulder Press", videoUrl: "https://www.youtube.com/watch?v=SyJ2H3beLVE" },
  { id: "shoulders-scrape-rack-tall-kneeling-shoulder-press", muscleGroup: "Shoulders", name: "Scrape Rack Tall Kneeling Shoulder Press", videoUrl: "https://www.youtube.com/watch?v=NJa4gfBErus" },
  { id: "shoulders-seated-alternating-arnold-press", muscleGroup: "Shoulders", name: "Seated Alternating Arnold Press", videoUrl: "https://www.youtube.com/watch?v=JrbKEX8QPis" },
  { id: "shoulders-seated-db-front-raise", muscleGroup: "Shoulders", name: "Seated DB Front Raise", videoUrl: "https://www.youtube.com/watch?v=GZYwvv9ajxs" },
  { id: "shoulders-seated-db-lateral-raise", muscleGroup: "Shoulders", name: "Seated DB Lateral Raise", videoUrl: "https://youtu.be/wKnAiy1nLOo" },
  { id: "shoulders-seated-db-lateral-raise-thumbs-up", muscleGroup: "Shoulders", name: "Seated DB Lateral Raise (Thumbs Up)", videoUrl: "https://www.youtube.com/watch?v=q7yLKtyknEM" },
  { id: "shoulders-seated-db-overhead-press", muscleGroup: "Shoulders", name: "Seated DB Overhead Press", videoUrl: "https://youtu.be/0JfYxMRsUCQ?t=8s" },
  { id: "shoulders-seated-one-arm-db-overhead-press", muscleGroup: "Shoulders", name: "Seated One-Arm DB Overhead Press", videoUrl: "https://www.youtube.com/watch?v=MZdT1-Bv9Dg" },
  { id: "shoulders-short-seated-knee-hug-press", muscleGroup: "Shoulders", name: "Short-Seated Knee Hug Press", videoUrl: "https://www.instagram.com/reel/CyGRN8NLU3V/?igsh=dWFobXM2NnN5b3V4" },
  { id: "shoulders-short-seated-landmine-press", muscleGroup: "Shoulders", name: "Short-Seated Landmine Press", videoUrl: "https://www.youtube.com/watch?v=NKGwU45E1Xk" },
  { id: "shoulders-side-plank-shoulder-press", muscleGroup: "Shoulders", name: "Side Plank Shoulder Press", videoUrl: "https://www.youtube.com/watch?v=dcNCZle5gM4" },
  { id: "shoulders-side-lying-lateral-raise", muscleGroup: "Shoulders", name: "Side-Lying Lateral Raise", videoUrl: "https://www.youtube.com/watch?v=XEKXovy2m7o" },
  { id: "shoulders-smith-machine-staggered-shoulder-press", muscleGroup: "Shoulders", name: "Smith Machine Staggered Shoulder Press", videoUrl: "https://youtu.be/RiJzYn4kklM?t=20" },
  { id: "shoulders-snatch-grip-shoulder-press", muscleGroup: "Shoulders", name: "Snatch-grip Shoulder Press", videoUrl: "https://www.youtube.com/watch?v=sb-JYheg8ZE" },
  { id: "shoulders-staggered-stance-front-raise", muscleGroup: "Shoulders", name: "Staggered Stance Front Raise", videoUrl: "https://www.youtube.com/watch?v=dpmAmEWeLp4&list=PLjru55YB4shrZUsWzy2xUKW4xX_Q2hM4p&index=13" },
  { id: "shoulders-staggered-stance-landmine-press", muscleGroup: "Shoulders", name: "Staggered Stance Landmine Press", videoUrl: "https://www.youtube.com/watch?v=q_3k7ff1awI" },
  { id: "shoulders-standing-barbell-overhead-press", muscleGroup: "Shoulders", name: "Standing Barbell Overhead Press", videoUrl: "https://www.youtube.com/watch?v=yL1GGUKfJHE" },
  { id: "shoulders-standing-cable-overhead-press", muscleGroup: "Shoulders", name: "Standing Cable Overhead Press", videoUrl: "https://www.youtube.com/watch?v=PqZNN-v8vJk" },
  { id: "shoulders-standing-db-overhead-press", muscleGroup: "Shoulders", name: "Standing DB Overhead Press", videoUrl: "https://www.youtube.com/watch?v=iygUkQBQ_Ks" },
  { id: "shoulders-standing-one-arm-landmine-press", muscleGroup: "Shoulders", name: "Standing One-Arm Landmine Press", videoUrl: "https://www.youtube.com/watch?v=_BFojLL1Dy8" },
  { id: "shoulders-sumo-press", muscleGroup: "Shoulders", name: "Sumo Press", videoUrl: "https://www.youtube.com/watch?v=zjPKScF5Xoc" },
  { id: "shoulders-suspended-y-raise", muscleGroup: "Shoulders", name: "Suspended Y-Raise", videoUrl: "https://www.youtube.com/watch?v=QKjeeqBQZ1Y" },
  { id: "shoulders-tall-kneeling-one-arm-overhead-press", muscleGroup: "Shoulders", name: "Tall-Kneeling One-Arm Overhead Press", videoUrl: "https://www.youtube.com/watch?v=45N-2_m7VI8" },
  { id: "rear-delts-band-bent-over-reverse-fly", muscleGroup: "Rear Delts", name: "Band Bent Over Reverse Fly", videoUrl: "https://www.youtube.com/watch?v=jSHpCaki5ls" },
  { id: "rear-delts-band-reverse-fly-w-handle", muscleGroup: "Rear Delts", name: "Band Reverse Fly w/Handle", videoUrl: "https://www.youtube.com/watch?v=38leTE2y1I8" },
  { id: "rear-delts-barbell-high-row", muscleGroup: "Rear Delts", name: "Barbell High Row", videoUrl: "https://www.youtube.com/watch?v=H6XtEta2S5A" },
  { id: "rear-delts-bent-over-db-reverse-fly", muscleGroup: "Rear Delts", name: "Bent Over DB Reverse Fly", videoUrl: "https://www.youtube.com/watch?v=ntc3WBgJ3-Q" },
  { id: "rear-delts-bent-over-reverse-fly-w-bottle", muscleGroup: "Rear Delts", name: "Bent Over Reverse Fly w/ bottle", videoUrl: "https://www.youtube.com/watch?v=1TDu3JbC-WY" },
  { id: "rear-delts-cable-reverse-fly", muscleGroup: "Rear Delts", name: "Cable Reverse Fly", videoUrl: "https://www.youtube.com/watch?v=8McrgUcHXQ4&t=2s" },
  { id: "rear-delts-cable-shoulder-pull", muscleGroup: "Rear Delts", name: "Cable Shoulder Pull", videoUrl: "https://www.youtube.com/watch?v=za8jmCs6LHg" },
  { id: "rear-delts-chest-supported-wide-db-row", muscleGroup: "Rear Delts", name: "Chest-Supported Wide DB Row", videoUrl: "https://www.youtube.com/watch?v=xiz7hPLRKFo" },
  { id: "rear-delts-db-high-row", muscleGroup: "Rear Delts", name: "DB High Row", videoUrl: "https://exrx.net/WeightExercises/DeltoidPosterior/DBRearDeltRow" },
  { id: "rear-delts-face-pull", muscleGroup: "Rear Delts", name: "Face Pull", videoUrl: "https://www.youtube.com/watch?v=JmHgk1e9YTE&feature=youtu.be" },
  { id: "rear-delts-face-pull-half-kneeling", muscleGroup: "Rear Delts", name: "Face Pull (Half-kneeling)", videoUrl: "https://youtu.be/ieJ9z19OJu4?t=109" },
  { id: "rear-delts-hanging-shoulder-depression", muscleGroup: "Rear Delts", name: "Hanging Shoulder Depression", videoUrl: "https://youtu.be/EGY6vcLQ_c4" },
  { id: "rear-delts-lying-face-pull", muscleGroup: "Rear Delts", name: "Lying Face Pull", videoUrl: "https://www.youtube.com/watch?v=_Rl3-yzWxJI" },
  { id: "rear-delts-lying-shoulder-pull", muscleGroup: "Rear Delts", name: "Lying Shoulder Pull", videoUrl: "https://www.youtube.com/watch?v=8fIPrLsCwwc" },
  { id: "rear-delts-machine-reverse-fly", muscleGroup: "Rear Delts", name: "Machine Reverse Fly", videoUrl: "https://www.youtube.com/watch?v=5YK4bgzXDp0" },
  { id: "rear-delts-meadows-row", muscleGroup: "Rear Delts", name: "Meadows row", videoUrl: "https://www.youtube.com/watch?v=bgq_N4xYhzI" },
  { id: "rear-delts-one-arm-face-pull", muscleGroup: "Rear Delts", name: "One-Arm Face Pull", videoUrl: "https://youtu.be/vWVtbOhnE_U?t=39" },
  { id: "rear-delts-one-arm-shoulder-pull", muscleGroup: "Rear Delts", name: "One-arm Shoulder Pull", videoUrl: "https://www.youtube.com/watch?v=5rp7Zag3fAM" },
  { id: "rear-delts-prone-rear-delt-fly", muscleGroup: "Rear Delts", name: "Prone Rear Delt Fly", videoUrl: "https://youtu.be/1AZpNa364fI?si=RzQfFtCOCom1oHty" },
  { id: "rear-delts-rear-delt-cable-pulldown", muscleGroup: "Rear Delts", name: "Rear Delt Cable Pulldown", videoUrl: "https://youtu.be/CVFYWE5GhjQ?t=1" },
  { id: "rear-delts-rear-delt-cable-row", muscleGroup: "Rear Delts", name: "Rear Delt Cable Row", videoUrl: "https://youtu.be/uIdXVGjcfFE?t=88" },
  { id: "rear-delts-reverse-fly-machine", muscleGroup: "Rear Delts", name: "Reverse Fly (Machine)", videoUrl: "https://www.youtube.com/watch?v=arVW-yXqx5Q" },
  { id: "rear-delts-seated-db-reverse-fly", muscleGroup: "Rear Delts", name: "Seated DB Reverse Fly", videoUrl: "https://youtu.be/EA7u4Q_8HQ0?t=45" },
  { id: "rear-delts-standing-cable-reverse-fly-w-external-rotatation", muscleGroup: "Rear Delts", name: "Standing Cable Reverse Fly w/ External Rotatation", videoUrl: "https://www.youtube.com/watch?v=5aMpvA1eoN4" },
  { id: "rear-delts-suspended-face-pull", muscleGroup: "Rear Delts", name: "Suspended Face Pull", videoUrl: "https://www.youtube.com/watch?v=03mYKk4B-6k" },
  { id: "rear-delts-suspended-wide-row-trx", muscleGroup: "Rear Delts", name: "Suspended Wide Row (TRX)", videoUrl: "https://www.youtube.com/watch?v=3GkKX3hWZ3Y&feature=youtu.be&t=38s" },
  { id: "rear-delts-trx-reverse-fly", muscleGroup: "Rear Delts", name: "TRX Reverse Fly", videoUrl: "https://www.youtube.com/watch?v=0gD4CRQc8UQ" },
  { id: "rear-delts-trx-shoulder-pull", muscleGroup: "Rear Delts", name: "TRX Shoulder Pull", videoUrl: "https://www.youtube.com/watch?v=xcDyO07cBng" },
  { id: "rear-delts-wide-barbell-row", muscleGroup: "Rear Delts", name: "Wide Barbell Row", videoUrl: "https://www.youtube.com/watch?v=mPZlcUYAtYw" },
  { id: "traps-barbell-shrug", muscleGroup: "Traps", name: "Barbell Shrug", videoUrl: "https://youtu.be/NAqCVe2mwzM?t=17s" },
  { id: "traps-barbell-shrug-behind-back", muscleGroup: "Traps", name: "Barbell Shrug (Behind Back)", videoUrl: "https://www.youtube.com/watch?v=OoUQRw91D94" },
  { id: "traps-cable-shrug-behind-back", muscleGroup: "Traps", name: "Cable Shrug (Behind Back)", videoUrl: "https://youtu.be/w4n8yPBQo-8?si=3vtNHOB_EiP4Lhxp&t=8" },
  { id: "traps-chest-supported-incline-shrug", muscleGroup: "Traps", name: "Chest Supported Incline Shrug", videoUrl: "https://www.youtube.com/watch?v=VXwCPj1U1a4" },
  { id: "traps-db-shrug", muscleGroup: "Traps", name: "DB Shrug", videoUrl: "https://youtu.be/g6qbq4Lf1FI?t=47s" },
  { id: "traps-front-rack-barbell-shrug", muscleGroup: "Traps", name: "Front Rack Barbell Shrug", videoUrl: "https://www.youtube.com/watch?v=ECvDmi1PaZw" },
  { id: "traps-monkey-shrug", muscleGroup: "Traps", name: "Monkey Shrug", videoUrl: "https://youtu.be/nfhZfzhgYBs?si=m9SYOW8d8n5GXiuU&t=42" },
  { id: "traps-overhead-shrug", muscleGroup: "Traps", name: "Overhead Shrug", videoUrl: "https://www.youtube.com/watch?v=9WNiA24I628" },
  { id: "traps-trap-bar-shrug", muscleGroup: "Traps", name: "Trap Bar Shrug", videoUrl: "https://www.youtube.com/watch?v=dAg1Kaevqj0" },
  { id: "traps-wide-cable-shrug", muscleGroup: "Traps", name: "Wide Cable Shrug", videoUrl: "https://www.youtube.com/watch?v=ckvh4Xw3kvc" },
  { id: "traps-wide-grip-barbell-shrug", muscleGroup: "Traps", name: "Wide-grip Barbell Shrug", videoUrl: "https://youtu.be/pqYr_lb04O4?t=47s" },
  { id: "back-horizontal-pull-band-seated-row", muscleGroup: "Back (Horizontal Pull)", name: "Band Seated Row", videoUrl: "https://www.youtube.com/watch?v=lHuGxZZ09nY" },
  { id: "back-horizontal-pull-band-standing-row-w-handle", muscleGroup: "Back (Horizontal Pull)", name: "Band Standing Row w/Handle", videoUrl: "https://youtu.be/oERBysMb-7c?t=58" },
  { id: "back-horizontal-pull-barbell-bent-over-row", muscleGroup: "Back (Horizontal Pull)", name: "Barbell Bent Over Row", videoUrl: "https://www.youtube.com/watch?v=VLsxhyUlFC8" },
  { id: "back-horizontal-pull-chest-supported-alternating-db-row", muscleGroup: "Back (Horizontal Pull)", name: "Chest-Supported Alternating DB Row", videoUrl: "https://www.youtube.com/watch?v=JTlTbKFX7ZI" },
  { id: "back-horizontal-pull-chest-supported-db-row", muscleGroup: "Back (Horizontal Pull)", name: "Chest-Supported DB Row", videoUrl: "https://www.youtube.com/watch?v=JzheQY8aqOY" },
  { id: "back-horizontal-pull-chest-supported-machine-row", muscleGroup: "Back (Horizontal Pull)", name: "Chest-Supported Machine Row", videoUrl: "https://www.youtube.com/watch?v=9WwRJQ003hU" },
  { id: "back-horizontal-pull-db-row-butt-to-wall", muscleGroup: "Back (Horizontal Pull)", name: "DB Row (Butt-to-wall)", videoUrl: "https://www.youtube.com/watch?v=ss3GiHTeDTw" },
  { id: "back-horizontal-pull-door-handle-row", muscleGroup: "Back (Horizontal Pull)", name: "Door Handle Row", videoUrl: "https://youtu.be/vGAK2-_kn1U?t=76" },
  { id: "back-horizontal-pull-feet-elevated-inverted-row", muscleGroup: "Back (Horizontal Pull)", name: "Feet Elevated Inverted Row", videoUrl: "https://www.youtube.com/watch?v=-gI2fDiURuE" },
  { id: "back-horizontal-pull-half-prone-db-row", muscleGroup: "Back (Horizontal Pull)", name: "Half-Prone DB Row", videoUrl: "https://youtube.com/shorts/_rTB0VQ9smA" },
  { id: "back-horizontal-pull-high-pull-technogym", muscleGroup: "Back (Horizontal Pull)", name: "High Pull Technogym", videoUrl: "https://www.youtube.com/watch?v=MT1ilMyBTWE" },
  { id: "back-horizontal-pull-inverted-row", muscleGroup: "Back (Horizontal Pull)", name: "Inverted Row", videoUrl: "https://youtu.be/9fItzuh9Iok?t=8" },
  { id: "back-horizontal-pull-landmine-row", muscleGroup: "Back (Horizontal Pull)", name: "Landmine Row", videoUrl: "https://www.youtube.com/watch?v=9hSQVBHLOX0" },
  { id: "back-horizontal-pull-long-seated-alternating-cable-row", muscleGroup: "Back (Horizontal Pull)", name: "Long-Seated Alternating Cable Row", videoUrl: "https://www.youtube.com/watch?v=N9vMyUpXqW4" },
  { id: "back-horizontal-pull-long-seated-one-arm-cable-row", muscleGroup: "Back (Horizontal Pull)", name: "Long-Seated One-Arm Cable Row", videoUrl: "https://www.youtube.com/watch?v=zW-TiK1Akg4" },
  { id: "back-horizontal-pull-low-oblique-one-arm-row", muscleGroup: "Back (Horizontal Pull)", name: "Low Oblique One-Arm Row", videoUrl: "https://www.youtube.com/shorts/IHXbLP6aV4c" },
  { id: "back-horizontal-pull-low-pull-technogym", muscleGroup: "Back (Horizontal Pull)", name: "Low Pull Technogym", videoUrl: "https://www.youtube.com/watch?v=jgjm74YJ0mk" },
  { id: "back-horizontal-pull-one-arm-db-row", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm DB Row", videoUrl: "https://www.youtube.com/watch?v=Wdv_3ojsPhU&feature=youtu.be" },
  { id: "back-horizontal-pull-one-arm-db-row-pronated-to-neutral", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm DB Row (Pronated to Neutral)", videoUrl: "https://www.youtube.com/watch?v=LhoWybY-Elo" },
  { id: "back-horizontal-pull-one-arm-db-row-w-torso-rotation", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm DB Row w/ Torso Rotation", videoUrl: "https://www.youtube.com/watch?v=cxtcS1zz9Vk" },
  { id: "back-horizontal-pull-one-arm-landmine-row", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm Landmine Row", videoUrl: "https://www.youtube.com/watch?v=8shgaY2G1tM" },
  { id: "back-horizontal-pull-one-arm-one-leg-db-row-contr", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm One-Leg DB Row (Contr)", videoUrl: "https://www.youtube.com/watch?v=0AOM6uODEAQ" },
  { id: "back-horizontal-pull-one-arm-one-leg-db-row-ips", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm One-Leg DB Row (Ips)", videoUrl: "https://youtu.be/MgLiXlgSeis?t=21" },
  { id: "back-horizontal-pull-one-arm-seated-cable-row", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm Seated Cable Row", videoUrl: "https://youtu.be/Sss7p8RyZYo?t=32" },
  { id: "back-horizontal-pull-one-arm-suspended-row", muscleGroup: "Back (Horizontal Pull)", name: "One-Arm Suspended Row", videoUrl: "https://www.youtube.com/watch?v=EB5XAbDg2u0" },
  { id: "back-horizontal-pull-pendlay-row", muscleGroup: "Back (Horizontal Pull)", name: "Pendlay Row", videoUrl: "https://youtu.be/ZlRrIsoDpKg" },
  { id: "back-horizontal-pull-ring-row", muscleGroup: "Back (Horizontal Pull)", name: "Ring Row", videoUrl: "https://youtu.be/ZVM4-F0ZF0w" },
  { id: "back-horizontal-pull-seated-cable-row", muscleGroup: "Back (Horizontal Pull)", name: "Seated Cable Row", videoUrl: "https://www.youtube.com/watch?v=4iNlLpIzT9w" },
  { id: "back-horizontal-pull-short-seated-band-alternating-row", muscleGroup: "Back (Horizontal Pull)", name: "Short-seated Band Alternating Row", videoUrl: "https://www.youtube.com/watch?v=LpuSXF-MtlE" },
  { id: "back-horizontal-pull-short-seated-one-arm-cable-row", muscleGroup: "Back (Horizontal Pull)", name: "Short-seated One-Arm Cable Row", videoUrl: "https://www.youtube.com/watch?v=uB1bKmPVTl8" },
  { id: "back-horizontal-pull-split-stance-one-arm-db-row", muscleGroup: "Back (Horizontal Pull)", name: "Split Stance One-Arm DB Row", videoUrl: "https://www.youtube.com/watch?v=ucPjGldA3TE" },
  { id: "back-horizontal-pull-standing-cross-body-cable-row", muscleGroup: "Back (Horizontal Pull)", name: "Standing Cross Body Cable Row", videoUrl: "https://youtu.be/zBpp2guXHXc?si=S9wC8brG_5FFH0hJ&t=5" },
  { id: "back-horizontal-pull-suspended-row", muscleGroup: "Back (Horizontal Pull)", name: "Suspended Row", videoUrl: "https://www.youtube.com/watch?v=ntzBt8o2O0k" },
  { id: "back-horizontal-pull-table-row", muscleGroup: "Back (Horizontal Pull)", name: "Table Row", videoUrl: "https://www.youtube.com/watch?v=FKKZRwBJDxE" },
  { id: "back-vertical-pull-90-90-db-pullover", muscleGroup: "Back (Vertical Pull)", name: "90/90 DB Pullover", videoUrl: "https://www.youtube.com/watch?v=tl4eWAS2VMI" },
  { id: "back-vertical-pull-aerial-hoop-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Aerial Hoop Chin-up", videoUrl: "https://www.youtube.com/shorts/QfPxX-8PYFY" },
  { id: "back-vertical-pull-alternating-db-pullover", muscleGroup: "Back (Vertical Pull)", name: "Alternating DB Pullover", videoUrl: "https://youtu.be/yw7KRDEr3HI?t=11" },
  { id: "back-vertical-pull-band-lat-prayer", muscleGroup: "Back (Vertical Pull)", name: "Band Lat Prayer", videoUrl: "https://www.youtube.com/watch?v=RzwqaJrjIz8" },
  { id: "back-vertical-pull-barbell-pullover", muscleGroup: "Back (Vertical Pull)", name: "Barbell Pullover", videoUrl: "https://www.youtube.com/watch?v=A6CH9uwUsRg" },
  { id: "back-vertical-pull-chest-supported-lat-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Chest-Supported Lat Pulldown", videoUrl: "https://youtu.be/zlFKRwk4T0E?t=8" },
  { id: "back-vertical-pull-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Chin-Up", videoUrl: "https://www.youtube.com/watch?v=OsNNdrhcT_I&feature=youtu.be" },
  { id: "back-vertical-pull-close-neutral-grip-lat-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Close Neutral Grip Lat Pulldown", videoUrl: "https://www.youtube.com/watch?v=kxeklf1Tkhw" },
  { id: "back-vertical-pull-db-pullover", muscleGroup: "Back (Vertical Pull)", name: "DB Pullover", videoUrl: "https://youtu.be/-oXVlHotHP4" },
  { id: "back-vertical-pull-decline-cable-pullover", muscleGroup: "Back (Vertical Pull)", name: "Decline Cable Pullover", videoUrl: "https://www.youtube.com/watch?v=xxH29yHmAuM" },
  { id: "back-vertical-pull-door-pull-up", muscleGroup: "Back (Vertical Pull)", name: "Door Pull-up", videoUrl: "https://youtu.be/02WC-IMkmhQ?t=33" },
  { id: "back-vertical-pull-eccentric-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Eccentric Chin-Up", videoUrl: "https://www.youtube.com/watch?v=Arw7D_k0MPg" },
  { id: "back-vertical-pull-eccentric-pull-up", muscleGroup: "Back (Vertical Pull)", name: "Eccentric Pull-up", videoUrl: "https://www.youtube.com/watch?v=hvhQXzJ4vhM" },
  { id: "back-vertical-pull-half-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Half Chin-up", videoUrl: "https://youtu.be/quWhk_n0PJY" },
  { id: "back-vertical-pull-half-pull-up", muscleGroup: "Back (Vertical Pull)", name: "Half Pull-Up", videoUrl: "https://www.youtube.com/watch?v=_o8SBJr--Pk" },
  { id: "back-vertical-pull-half-kneeling-one-arm-lat-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Half-Kneeling One-Arm Lat Pulldown", videoUrl: "https://www.youtube.com/watch?v=XbZgoSNJXm4" },
  { id: "back-vertical-pull-half-kneeling-straight-arm-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Half-Kneeling Straight-Arm Pulldown", videoUrl: "https://www.youtube.com/shorts/PtuulRImLuo" },
  { id: "back-vertical-pull-half-kneeling-cross-body-lat-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Half-kneeling Cross Body Lat Pulldown", videoUrl: "https://youtube.com/shorts/VLsGVlTJT8s" },
  { id: "back-vertical-pull-high-oblique-one-arm-pulldown", muscleGroup: "Back (Vertical Pull)", name: "High Oblique One-Arm Pulldown", videoUrl: "https://www.youtube.com/watch?v=Mmkqd8jscKw" },
  { id: "back-vertical-pull-l-sit-chin-up", muscleGroup: "Back (Vertical Pull)", name: "L-Sit Chin-up", videoUrl: "https://www.youtube.com/watch?v=W0PI19ZzV_I" },
  { id: "back-vertical-pull-lat-prayer", muscleGroup: "Back (Vertical Pull)", name: "Lat Prayer", videoUrl: "https://www.youtube.com/watch?v=P86gE4V8nFU" },
  { id: "back-vertical-pull-long-seated-alternating-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Long-Seated Alternating Pulldown", videoUrl: "https://www.youtube.com/watch?v=MLplh9JrLVg" },
  { id: "back-vertical-pull-long-seated-one-arm-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Long-Seated One-Arm Pulldown", videoUrl: "https://www.youtube.com/watch?v=48EwkqR2nW0" },
  { id: "back-vertical-pull-long-seated-reverse-grip-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Long-Seated Reverse Grip Pulldown", videoUrl: "https://www.youtube.com/watch?v=czqTAA8JOF8" },
  { id: "back-vertical-pull-machine-lat-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Machine Lat Pulldown", videoUrl: "https://youtu.be/kwJeh3QyhVE?si=C8xZLP_RuitJBt0j&t=37" },
  { id: "back-vertical-pull-neutral-grip-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Neutral Grip Chin-up", videoUrl: "https://exrx.net/WeightExercises/LatissimusDorsi/BWCloseGripChinup" },
  { id: "back-vertical-pull-neutral-grip-lat-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Neutral Grip Lat Pulldown", videoUrl: "https://youtu.be/kVB6SlEyjQM?t=237" },
  { id: "back-vertical-pull-neutral-grip-eccentric-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Neutral-grip Eccentric Chin-Up", videoUrl: "https://www.youtube.com/watch?v=Yi1UzoN8YpY" },
  { id: "back-vertical-pull-one-arm-motorcycle-row", muscleGroup: "Back (Vertical Pull)", name: "One-Arm Motorcycle row", videoUrl: "https://www.youtube.com/watch?v=jp02bDes1i0" },
  { id: "back-vertical-pull-one-arm-pulldown", muscleGroup: "Back (Vertical Pull)", name: "One-arm Pulldown", videoUrl: "https://www.youtube.com/watch?v=HBC5s98wXko" },
  { id: "back-vertical-pull-one-arm-pulldown-neutral", muscleGroup: "Back (Vertical Pull)", name: "One-arm Pulldown (Neutral)", videoUrl: "https://youtu.be/0BT533ueEdI?t=45" },
  { id: "back-vertical-pull-one-arm-pulldown-supinated", muscleGroup: "Back (Vertical Pull)", name: "One-arm Pulldown (Supinated)", videoUrl: "https://www.youtube.com/watch?v=Hz9vEDzusu4" },
  { id: "back-vertical-pull-overhand-pull-up", muscleGroup: "Back (Vertical Pull)", name: "Overhand Pull-Up", videoUrl: "https://www.exrx.net/WeightExercises/LatissimusDorsi/BWPullup" },
  { id: "back-vertical-pull-overhand-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Overhand Pulldown", videoUrl: "https://www.youtube.com/watch?v=yYsjL7qNMsU" },
  { id: "back-vertical-pull-pronated-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Pronated Chin-up", videoUrl: "https://www.youtube.com/watch?v=un6HKZo2Mhs" },
  { id: "back-vertical-pull-ring-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Ring Chin-up", videoUrl: "https://www.youtube.com/watch?v=S88cK91R1Wo" },
  { id: "back-vertical-pull-rope-straight-arm-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Rope Straight-Arm Pulldown", videoUrl: "https://www.youtube.com/watch?v=EurcOa-r9r4" },
  { id: "back-vertical-pull-seated-cable-pullover", muscleGroup: "Back (Vertical Pull)", name: "Seated Cable Pullover", videoUrl: "https://www.youtube.com/watch?v=9RDq0UC1ICo" },
  { id: "back-vertical-pull-seated-one-arm-pulldown-w-both-knee-hug", muscleGroup: "Back (Vertical Pull)", name: "Seated One-Arm Pulldown w/ Both Knee Hug", videoUrl: "https://www.youtube.com/shorts/W7Zwu-Pra7U" },
  { id: "back-vertical-pull-seated-one-arm-pulldown-w-knee-hug", muscleGroup: "Back (Vertical Pull)", name: "Seated One-Arm Pulldown w/ Knee Hug", videoUrl: "https://www.youtube.com/watch?v=VJl5WSCKt1g" },
  { id: "back-vertical-pull-short-seated-alternating-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Short-Seated Alternating Pulldown", videoUrl: "https://youtu.be/sxmBuWzZlJ4?t=5" },
  { id: "back-vertical-pull-short-seated-neutral-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Short-Seated Neutral Pulldown", videoUrl: "https://www.youtube.com/watch?v=oyOr6nFtja0" },
  { id: "back-vertical-pull-short-seated-one-arm-lat-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Short-Seated One-Arm Lat Pulldown", videoUrl: "https://www.youtube.com/watch?v=5J4hkJYdxr0" },
  { id: "back-vertical-pull-staggered-stance-straight-arm-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Staggered Stance Straight-Arm Pulldown", videoUrl: "https://www.youtube.com/watch?v=a7C_Rh6RQxk" },
  { id: "back-vertical-pull-standing-lat-prayer", muscleGroup: "Back (Vertical Pull)", name: "Standing Lat Prayer", videoUrl: "https://www.youtube.com/watch?v=G9uNaXGTJ4w" },
  { id: "back-vertical-pull-straight-arm-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Straight-Arm Pulldown", videoUrl: "https://youtu.be/wcVDItawocI?t=4" },
  { id: "back-vertical-pull-supinated-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Supinated Pulldown", videoUrl: "https://www.youtube.com/watch?v=i5jUwlAYyPo" },
  { id: "back-vertical-pull-trx-pull-up", muscleGroup: "Back (Vertical Pull)", name: "TRX Pull-up", videoUrl: "https://www.youtube.com/watch?v=fAQwN4t-2JI" },
  { id: "back-vertical-pull-top-half-chin-up", muscleGroup: "Back (Vertical Pull)", name: "Top Half Chin-up", videoUrl: "https://www.youtube.com/shorts/KCKAAKFGAA4" },
  { id: "back-vertical-pull-wide-neutral-grip-pulldown", muscleGroup: "Back (Vertical Pull)", name: "Wide Neutral-grip Pulldown", videoUrl: "https://www.youtube.com/watch?v=z_eJ4iAb-lg" },
  { id: "biceps-alternating-cable-preacher-curl", muscleGroup: "Biceps", name: "Alternating Cable Preacher Curl", videoUrl: "https://www.youtube.com/watch?v=Ceu4HsRlF-M" },
  { id: "biceps-alternating-db-curl", muscleGroup: "Biceps", name: "Alternating DB Curl", videoUrl: "https://www.youtube.com/watch?v=WYezBGuUsdw" },
  { id: "biceps-alternating-db-hammer-preacher-curls", muscleGroup: "Biceps", name: "Alternating DB Hammer Preacher Curls", videoUrl: "https://www.youtube.com/watch?v=xdgvGlLxyEY" },
  { id: "biceps-alternating-db-preacher-curl", muscleGroup: "Biceps", name: "Alternating DB Preacher Curl", videoUrl: "https://www.youtube.com/watch?v=GZjgjtCN3J4" },
  { id: "biceps-alternating-spider-curl", muscleGroup: "Biceps", name: "Alternating Spider Curl", videoUrl: "https://youtu.be/KznrM_RhXDc" },
  { id: "biceps-band-bicep-curl", muscleGroup: "Biceps", name: "Band Bicep Curl", videoUrl: "https://www.youtube.com/watch?v=3g-1J2KkX_8" },
  { id: "biceps-bayesian-curl", muscleGroup: "Biceps", name: "Bayesian Curl", videoUrl: "https://www.youtube.com/watch?v=Vd8MNCeqRA4" },
  { id: "biceps-cable-bicep-curl", muscleGroup: "Biceps", name: "Cable Bicep Curl", videoUrl: "https://youtu.be/GAfhJiXIl24" },
  { id: "biceps-cable-preacher-curl", muscleGroup: "Biceps", name: "Cable Preacher Curl", videoUrl: "https://youtu.be/HssKSVyJ6EU?t=11" },
  { id: "biceps-cable-rope-twist-curl", muscleGroup: "Biceps", name: "Cable Rope Twist Curl", videoUrl: "https://www.youtube.com/watch?v=sR_EdrSruyQ&feature=youtu.be" },
  { id: "biceps-db-concentration-curl", muscleGroup: "Biceps", name: "DB Concentration Curl", videoUrl: "https://www.youtube.com/watch?v=AcDbH6yZk4k" },
  { id: "biceps-db-preacher-curl", muscleGroup: "Biceps", name: "DB Preacher Curl", videoUrl: "https://www.youtube.com/watch?v=JFXLD7NaDEI" },
  { id: "biceps-db-spider-curl", muscleGroup: "Biceps", name: "DB Spider Curl", videoUrl: "https://www.youtube.com/watch?v=y_GK6fn7raU&feature=youtu.be" },
  { id: "biceps-db-spider-hammer-curl", muscleGroup: "Biceps", name: "DB Spider Hammer Curl", videoUrl: "https://www.youtube.com/watch?v=tfEtA01r5SI" },
  { id: "biceps-dual-cable-bicep-curl-facing-away", muscleGroup: "Biceps", name: "Dual Cable Bicep Curl (Facing Away)", videoUrl: "https://www.youtube.com/watch?v=xrQlkUQCKQY" },
  { id: "biceps-facing-cable-bicep-curl-fwd-lean", muscleGroup: "Biceps", name: "Facing Cable Bicep Curl (Fwd Lean)", videoUrl: "https://www.youtube.com/watch?v=9OwqRKsrQ4w" },
  { id: "biceps-hammer-concentration-curl", muscleGroup: "Biceps", name: "Hammer Concentration Curl", videoUrl: "https://www.youtube.com/watch?v=5eJLufkiSik&feature=youtu.be" },
  { id: "biceps-hammer-curl", muscleGroup: "Biceps", name: "Hammer Curl", videoUrl: "https://www.youtube.com/watch?v=P5sXHLmXmBM" },
  { id: "biceps-hammer-preacher-curl", muscleGroup: "Biceps", name: "Hammer Preacher Curl", videoUrl: "https://youtu.be/hFylSwPh6Uk?t=14" },
  { id: "biceps-incline-bench-db-curl", muscleGroup: "Biceps", name: "Incline Bench DB Curl", videoUrl: "https://youtu.be/L0UeTFhGYfw?t=17s" },
  { id: "biceps-machine-preacher-curl", muscleGroup: "Biceps", name: "Machine Preacher Curl", videoUrl: "https://www.youtube.com/watch?v=Ja6ZlIDONac" },
  { id: "biceps-offset-db-curl", muscleGroup: "Biceps", name: "Offset DB Curl", videoUrl: "https://www.youtube.com/watch?v=jrcj9kVycdo" },
  { id: "biceps-one-arm-facing-cable-bicep-curl", muscleGroup: "Biceps", name: "One-Arm Facing Cable Bicep Curl", videoUrl: "https://youtube.com/shorts/nWr6ET9sAoA?feature=share" },
  { id: "biceps-one-arm-isometric-db-curl", muscleGroup: "Biceps", name: "One-Arm Isometric DB Curl", videoUrl: "https://www.youtube.com/watch?v=iJrid1uPtzE" },
  { id: "biceps-seated-supinated-db-curl", muscleGroup: "Biceps", name: "Seated Supinated DB Curl", videoUrl: "https://www.youtube.com/watch?v=OFgGcSYEtVI" },
  { id: "biceps-squated-cable-preacher-curl", muscleGroup: "Biceps", name: "Squated Cable Preacher Curl", videoUrl: "https://www.youtube.com/watch?v=MmUv_Lnc7QU" },
  { id: "biceps-standing-barbell-curl", muscleGroup: "Biceps", name: "Standing Barbell Curl", videoUrl: "https://www.youtube.com/watch?v=MI06f56sh8g" },
  { id: "biceps-standing-ez-curl", muscleGroup: "Biceps", name: "Standing EZ Curl", videoUrl: "https://www.youtube.com/watch?v=-gSM-kqNlUw" },
  { id: "biceps-standing-one-arm-db-curl", muscleGroup: "Biceps", name: "Standing One-Arm DB Curl", videoUrl: "https://www.youtube.com/watch?v=cEPxdYPP4to&feature=youtu.be" },
  { id: "biceps-suspended-bicep-curl", muscleGroup: "Biceps", name: "Suspended Bicep Curl", videoUrl: "https://www.youtube.com/watch?v=xG57S0fgXAk" },
  { id: "biceps-trx-bicep-curl", muscleGroup: "Biceps", name: "TRX Bicep Curl", videoUrl: "https://www.youtube.com/watch?v=xG57S0fgXAk" },
  { id: "triceps-alternating-db-skullcrusher", muscleGroup: "Triceps", name: "Alternating DB Skullcrusher", videoUrl: "https://www.youtube.com/watch?v=4PptnYMd61k" },
  { id: "triceps-band-overhead-tricep-extension", muscleGroup: "Triceps", name: "Band Overhead Tricep Extension", videoUrl: "https://youtu.be/a5rUdCeTtSE?t=4" },
  { id: "triceps-band-tricep-pushdown", muscleGroup: "Triceps", name: "Band Tricep Pushdown", videoUrl: "https://www.youtube.com/watch?v=1GT_xqd_sXc" },
  { id: "triceps-bent-over-cable-overhead-triceps-extension", muscleGroup: "Triceps", name: "Bent Over Cable Overhead Triceps Extension", videoUrl: "https://www.youtube.com/watch?v=ur3v50r9qzo" },
  { id: "triceps-bodyweight-tricep-pushdown", muscleGroup: "Triceps", name: "Bodyweight Tricep Pushdown", videoUrl: "https://youtu.be/4UXZtR-rIoY?si=WZXfdllI-Z5Oe_yB&t=4" },
  { id: "triceps-cable-overhead-triceps-extension", muscleGroup: "Triceps", name: "Cable Overhead Triceps Extension", videoUrl: "https://www.youtube.com/watch?v=mRozZKkGIfg" },
  { id: "triceps-cable-tricep-kickback", muscleGroup: "Triceps", name: "Cable Tricep Kickback", videoUrl: "https://www.youtube.com/watch?v=8yTabH46T1s&t=109s" },
  { id: "triceps-cross-cable-tricep-extension", muscleGroup: "Triceps", name: "Cross Cable Tricep Extension", videoUrl: "https://youtube.com/shorts/uID8NFK1p5Y?feature=share" },
  { id: "triceps-db-skull-over", muscleGroup: "Triceps", name: "DB Skull-over", videoUrl: "https://www.youtube.com/watch?v=e3Qki6C7azo" },
  { id: "triceps-db-skullcrusher", muscleGroup: "Triceps", name: "DB Skullcrusher", videoUrl: "https://youtu.be/ir5PsbniVSc?t=25" },
  { id: "triceps-decline-db-skullcrusher", muscleGroup: "Triceps", name: "Decline DB Skullcrusher", videoUrl: "https://youtu.be/1G7wKVKxIGU?t=8" },
  { id: "triceps-diamond-push-up", muscleGroup: "Triceps", name: "Diamond Push-Up", videoUrl: "https://www.youtube.com/watch?v=J0DnG1_S92I" },
  { id: "triceps-ez-skullcrusher", muscleGroup: "Triceps", name: "EZ Skullcrusher", videoUrl: "https://youtu.be/d_KZxkY_0cM?t=1m29s" },
  { id: "triceps-kneeling-cable-tricep-kickback", muscleGroup: "Triceps", name: "Kneeling Cable Tricep Kickback", videoUrl: "https://youtu.be/BomH5ZO7CDo?t=11" },
  { id: "triceps-lying-crossover-db-tricep-extension", muscleGroup: "Triceps", name: "Lying Crossover DB Tricep Extension", videoUrl: "https://youtu.be/vHWdgOM5fRc?t=63" },
  { id: "triceps-one-arm-cable-overhead-extension", muscleGroup: "Triceps", name: "One-Arm Cable Overhead Extension", videoUrl: "https://youtu.be/je8iFz9nk18?t=7s" },
  { id: "triceps-one-arm-cable-tricep-pushdown", muscleGroup: "Triceps", name: "One-Arm Cable Tricep Pushdown", videoUrl: "https://youtu.be/hFwJ7HrbORM?t=230" },
  { id: "triceps-one-arm-cross-body-cable-tricep-push-down", muscleGroup: "Triceps", name: "One-Arm Cross Body Cable Tricep Push-down", videoUrl: "https://youtube.com/shorts/f85IuVr_K5U?feature=share" },
  { id: "triceps-one-arm-db-overhead-extension", muscleGroup: "Triceps", name: "One-Arm DB Overhead Extension", videoUrl: "https://youtu.be/jTQWYdWLvys?t=47s" },
  { id: "triceps-overhead-cross-cable-tricep-extension", muscleGroup: "Triceps", name: "Overhead Cross-Cable Tricep Extension", videoUrl: "https://youtu.be/jtLTcED38Dg?t=16" },
  { id: "triceps-overhead-db-tricep-extension", muscleGroup: "Triceps", name: "Overhead DB Tricep Extension", videoUrl: "https://youtu.be/nRiJVZDpdL0?t=18" },
  { id: "triceps-reverse-grip-cross-body-tricep-push-down", muscleGroup: "Triceps", name: "Reverse Grip Cross Body Tricep Push-down", videoUrl: "https://www.youtube.com/shorts/HwkgQ7wH5_I" },
  { id: "triceps-reverse-tricep-pushdown", muscleGroup: "Triceps", name: "Reverse Tricep Pushdown", videoUrl: "https://www.youtube.com/watch?v=Q1_WXKQV8aE" },
  { id: "triceps-reverse-tricep-pushdown-w-forward-lean", muscleGroup: "Triceps", name: "Reverse Tricep Pushdown w/ Forward Lean", videoUrl: "https://youtu.be/NnLR4GiAFHA" },
  { id: "triceps-ring-tricep-extension", muscleGroup: "Triceps", name: "Ring Tricep Extension", videoUrl: "https://youtu.be/pm_iMTO2ysU" },
  { id: "triceps-rope-tricep-pushdown-w-forward-lean", muscleGroup: "Triceps", name: "Rope Tricep Pushdown w/Forward Lean", videoUrl: "https://www.youtube.com/watch?v=e5aj8hhCPkA" },
  { id: "triceps-skull-over", muscleGroup: "Triceps", name: "Skull-over", videoUrl: "https://www.youtube.com/watch?v=EMTJG2pGpas" },
  { id: "triceps-trx-tricep-extension", muscleGroup: "Triceps", name: "TRX Tricep Extension", videoUrl: "https://www.youtube.com/watch?v=u9FPqSe5cZs" },
  { id: "triceps-tricep-push-down", muscleGroup: "Triceps", name: "Tricep Push-Down", videoUrl: "https://www.youtube.com/watch?v=T6lUC2_Fpps" },
  { id: "triceps-tricep-pushdown-w-forward-lean", muscleGroup: "Triceps", name: "Tricep Pushdown w/Forward Lean", videoUrl: "https://www.youtube.com/shorts/z5cvLKL57-0" },
  { id: "quads-airborne-lunge", muscleGroup: "Quads", name: "Airborne Lunge", videoUrl: "https://www.youtube.com/watch?v=xtbax81_rWw" },
  { id: "quads-bw-lateral-step-down", muscleGroup: "Quads", name: "BW Lateral Step-down", videoUrl: "https://www.youtube.com/watch?v=PrZg_2VbzBE" },
  { id: "quads-back-squat", muscleGroup: "Quads", name: "Back Squat", videoUrl: "https://www.youtube.com/watch?v=_nJsqWcYInA&list=PL2vvPjRDHAuSMjjq3sOm1XT6h-pFxcG9c&index=2" },
  { id: "quads-back-squat-heels-elevated", muscleGroup: "Quads", name: "Back Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=ecPqXxvoOqY" },
  { id: "quads-back-squat-to-box", muscleGroup: "Quads", name: "Back Squat to Box", videoUrl: "https://www.youtube.com/watch?v=7iw2gLZKZ0w" },
  { id: "quads-band-leg-extension", muscleGroup: "Quads", name: "Band Leg Extension", videoUrl: "https://youtu.be/wY4Jg5t8SAU?t=6" },
  { id: "quads-band-split-squat", muscleGroup: "Quads", name: "Band Split Squat", videoUrl: "https://youtu.be/SaCR2ppXKnc?t=5" },
  { id: "quads-band-squat", muscleGroup: "Quads", name: "Band Squat", videoUrl: "https://www.youtube.com/watch?v=duP-UZsfOaQ" },
  { id: "quads-bent-over-step-up", muscleGroup: "Quads", name: "Bent Over Step-up", videoUrl: "https://www.youtube.com/watch?v=7SGC9eWP5uE" },
  { id: "quads-bodyweight-squat", muscleGroup: "Quads", name: "Bodyweight Squat", videoUrl: "https://www.youtube.com/watch?v=lzAMYKR9sfs&feature=youtu.be" },
  { id: "quads-bulgarian-split-squat-from-deficit", muscleGroup: "Quads", name: "Bulgarian Split Squat from Deficit", videoUrl: "https://www.youtube.com/watch?v=Vt5IfPNkVpg" },
  { id: "quads-cable-zercher-squat", muscleGroup: "Quads", name: "Cable Zercher Squat", videoUrl: "https://www.youtube.com/watch?v=BKNeeL229aA" },
  { id: "quads-cable-zercher-squat-heels-elevated", muscleGroup: "Quads", name: "Cable Zercher Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=0Lk1alFLTN8" },
  { id: "quads-cable-zercher-squat-to-box-heels-elevated", muscleGroup: "Quads", name: "Cable Zercher Squat to Box (Heels Elevated)", videoUrl: "https://www.youtube.com/shorts/IWGEVaZ265s" },
  { id: "quads-cossack-squat", muscleGroup: "Quads", name: "Cossack Squat", videoUrl: "https://youtu.be/45PTpRDktYU" },
  { id: "quads-cross-body-one-leg-leg-extension", muscleGroup: "Quads", name: "Cross Body One-leg Leg Extension", videoUrl: "https://www.youtube.com/shorts/jI7qSFexqn8" },
  { id: "quads-crossover-cable-step-up", muscleGroup: "Quads", name: "Crossover Cable Step-up", videoUrl: "https://youtube.com/shorts/3V7TA32nBFU" },
  { id: "quads-crossover-step-up", muscleGroup: "Quads", name: "Crossover Step-up", videoUrl: "https://www.youtube.com/watch?v=oQxyhAu7Q5M" },
  { id: "quads-db-split-squat", muscleGroup: "Quads", name: "DB Split Squat", videoUrl: "https://www.youtube.com/watch?v=GU8jP9spRwc" },
  { id: "quads-db-squat-heels-elevated", muscleGroup: "Quads", name: "DB Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=MFANqZ3_T90" },
  { id: "quads-db-step-up", muscleGroup: "Quads", name: "DB Step-up", videoUrl: "https://www.youtube.com/watch?v=37tVohr7LcE" },
  { id: "quads-db-step-up-contr", muscleGroup: "Quads", name: "DB Step-up (Contr)", videoUrl: "https://www.youtube.com/watch?v=QkdZxIRlC-Y" },
  { id: "quads-db-step-up-ipsilateral-load", muscleGroup: "Quads", name: "DB Step-up (Ipsilateral Load)", videoUrl: "https://www.youtube.com/watch?v=VPRPDz4ioZQ" },
  { id: "quads-double-kb-front-squat", muscleGroup: "Quads", name: "Double KB Front Squat", videoUrl: "https://www.youtube.com/watch?v=yv1Nygxx7rk" },
  { id: "quads-double-kb-front-squat-heels-elevated", muscleGroup: "Quads", name: "Double KB Front Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=Q_ByaCDHSpk" },
  { id: "quads-eccentric-overload-leg-extensions", muscleGroup: "Quads", name: "Eccentric Overload Leg Extensions", videoUrl: "https://www.youtube.com/watch?v=tmndFWa6ClQ" },
  { id: "quads-eccentric-rear-foot-elevated-split-squat", muscleGroup: "Quads", name: "Eccentric Rear Foot Elevated Split Squat", videoUrl: "https://www.youtube.com/watch?v=oQ2RXaXsP_E" },
  { id: "quads-foam-roller-db-squat", muscleGroup: "Quads", name: "Foam Roller DB Squat", videoUrl: "https://www.youtube.com/watch?v=d6LtwY-5pn8" },
  { id: "quads-foam-roller-goblet-squat", muscleGroup: "Quads", name: "Foam Roller Goblet Squat", videoUrl: "https://www.youtube.com/watch?v=T7j-SH6WWWA" },
  { id: "quads-front-foot-elevated-split-squat", muscleGroup: "Quads", name: "Front Foot Elevated Split Squat", videoUrl: "https://www.youtube.com/watch?v=rZu4ufWl1pE" },
  { id: "quads-front-heel-elevated-rear-foot-elevated-split-squat", muscleGroup: "Quads", name: "Front Heel Elevated Rear Foot Elevated Split Squat", videoUrl: "https://www.youtube.com/watch?v=N6qw4qeK7m8" },
  { id: "quads-front-heel-elevated-split-squat", muscleGroup: "Quads", name: "Front Heel Elevated Split Squat", videoUrl: "https://www.youtube.com/watch?v=mtLspkp3A7k" },
  { id: "quads-front-rack-db-squat", muscleGroup: "Quads", name: "Front Rack DB Squat", videoUrl: "https://www.youtube.com/watch?v=7CuKlSgu1B0" },
  { id: "quads-front-rack-split-squat", muscleGroup: "Quads", name: "Front Rack Split Squat", videoUrl: "https://www.youtube.com/watch?v=VsgCBIQE8gU" },
  { id: "quads-front-rack-squat-to-box", muscleGroup: "Quads", name: "Front Rack Squat to Box", videoUrl: "https://www.youtube.com/watch?v=o8R9B1t-Kv0" },
  { id: "quads-front-squat", muscleGroup: "Quads", name: "Front Squat", videoUrl: "https://www.youtube.com/watch?v=mMiVlL53_sA" },
  { id: "quads-front-squat-heels-elevated", muscleGroup: "Quads", name: "Front Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=pR8cDUWU7fA" },
  { id: "quads-front-squat-crossover-grip", muscleGroup: "Quads", name: "Front Squat Crossover Grip", videoUrl: "https://www.youtube.com/watch?v=2Ratk4lZKyI" },
  { id: "quads-front-squat-to-box", muscleGroup: "Quads", name: "Front Squat to Box", videoUrl: "https://www.youtube.com/watch?v=1LMVudQaIG0" },
  { id: "quads-front-squat-to-box-heels-elevated", muscleGroup: "Quads", name: "Front Squat to Box (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=C9FgQ-HM24o" },
  { id: "quads-front-squat-w-straps", muscleGroup: "Quads", name: "Front Squat w/Straps", videoUrl: "https://www.youtube.com/watch?v=PV6NoUZBYjU" },
  { id: "quads-gliding-leg-extension", muscleGroup: "Quads", name: "Gliding Leg Extension", videoUrl: "https://youtu.be/XZ3VAxt6yfg" },
  { id: "quads-goblet-lateral-lunge", muscleGroup: "Quads", name: "Goblet Lateral Lunge", videoUrl: "https://www.youtube.com/watch?v=DuoFCr4B_yA" },
  { id: "quads-goblet-lateral-step-down", muscleGroup: "Quads", name: "Goblet Lateral Step-down", videoUrl: "https://www.youtube.com/watch?v=aeZqZ3sKV8U" },
  { id: "quads-goblet-split-squat", muscleGroup: "Quads", name: "Goblet Split Squat", videoUrl: "https://www.youtube.com/watch?v=bf03qSMQfWc" },
  { id: "quads-goblet-split-squat-w-rotation", muscleGroup: "Quads", name: "Goblet Split Squat w/Rotation", videoUrl: "https://www.youtube.com/watch?v=pqrazr724Pk" },
  { id: "quads-goblet-squat", muscleGroup: "Quads", name: "Goblet Squat", videoUrl: "https://www.youtube.com/watch?v=gCESNsDsbqk" },
  { id: "quads-goblet-squat-heels-elevated", muscleGroup: "Quads", name: "Goblet Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=gpNky6gvseQ" },
  { id: "quads-goblet-squat-to-box", muscleGroup: "Quads", name: "Goblet Squat to box", videoUrl: "https://www.youtube.com/watch?v=mIJub2k6YNg" },
  { id: "quads-goblet-squat-to-box-heels-elevated", muscleGroup: "Quads", name: "Goblet Squat to box (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=Mmla01eCZHk" },
  { id: "quads-hack-squat", muscleGroup: "Quads", name: "Hack Squat", videoUrl: "https://youtu.be/0tn5K9NlCfo?t=5" },
  { id: "quads-hack-squat-reverse-banded", muscleGroup: "Quads", name: "Hack Squat (Reverse Banded)", videoUrl: "https://www.youtube.com/watch?v=JhMHmJG7v98" },
  { id: "quads-heel-tap-lateral-step-down", muscleGroup: "Quads", name: "Heel Tap Lateral Step-Down", videoUrl: "https://www.youtube.com/watch?v=cSrZDrgXsGI" },
  { id: "quads-high-step-up", muscleGroup: "Quads", name: "High Step-up", videoUrl: "https://www.youtube.com/watch?v=KGyVfgh0fhk" },
  { id: "quads-iso-wall-squat", muscleGroup: "Quads", name: "Iso Wall Squat", videoUrl: "https://youtu.be/xvJjIu6e5gw?si=bNdGeoUsXGXJ3zrx&t=18" },
  { id: "quads-iso-wall-squat-w-band", muscleGroup: "Quads", name: "Iso Wall Squat w/Band", videoUrl: "https://www.youtube.com/watch?v=tBho2u-cQRM" },
  { id: "quads-jefferson-split-squat", muscleGroup: "Quads", name: "Jefferson Split Squat", videoUrl: "https://www.youtube.com/shorts/Fc5OLQs7XDs" },
  { id: "quads-landmine-squat", muscleGroup: "Quads", name: "Landmine Squat", videoUrl: "https://youtu.be/hfzvlN-2MMg" },
  { id: "quads-lateral-lunge-contr-hold", muscleGroup: "Quads", name: "Lateral Lunge (Contr Hold)", videoUrl: "https://www.youtube.com/watch?v=UNvFTz8DzoQ" },
  { id: "quads-leg-extension", muscleGroup: "Quads", name: "Leg Extension", videoUrl: "https://www.youtube.com/watch?v=O5g-8F7y_ZY" },
  { id: "quads-leg-extension-5-second-pause", muscleGroup: "Quads", name: "Leg Extension 5 Second Pause", videoUrl: "https://www.youtube.com/watch?v=52hfKhXKRc8" },
  { id: "quads-leg-extension-isometric", muscleGroup: "Quads", name: "Leg Extension Isometric", videoUrl: "https://youtu.be/MqPL5bRZ3gc?t=14" },
  { id: "quads-leg-press", muscleGroup: "Quads", name: "Leg Press", videoUrl: "https://youtu.be/VFk3RzndUEc?t=39" },
  { id: "quads-leg-press-closed-chain", muscleGroup: "Quads", name: "Leg Press (Closed Chain)", videoUrl: "https://youtu.be/8EMbB0tCn7Q?si=qJTGNPMxSpA-sv4t&t=4" },
  { id: "quads-leg-press-open-chain", muscleGroup: "Quads", name: "Leg Press (Open Chain)", videoUrl: "https://youtu.be/IZxyjW7MPJQ?si=GfSNBd16T4sCXpBJ&t=12" },
  { id: "quads-low-cable-front-foot-elevated-split-squat", muscleGroup: "Quads", name: "Low Cable Front Foot Elevated Split Squat", videoUrl: "https://www.youtube.com/watch?v=eeJJMRwlU-w" },
  { id: "quads-low-cable-squat", muscleGroup: "Quads", name: "Low Cable Squat", videoUrl: "https://www.youtube.com/watch?v=X60Uv2Fftkg" },
  { id: "quads-low-cable-step-up", muscleGroup: "Quads", name: "Low Cable Step-up", videoUrl: "https://www.youtube.com/shorts/DLfG_Aobr78" },
  { id: "quads-low-step-down", muscleGroup: "Quads", name: "Low Step-down", videoUrl: "https://youtu.be/AoS5qiAg9xM?t=54s" },
  { id: "quads-low-bar-back-squat", muscleGroup: "Quads", name: "Low-bar Back Squat", videoUrl: "https://www.youtube.com/watch?v=74yZOaBrHZA&feature=youtu.be" },
  { id: "quads-offset-front-rack-db-squat", muscleGroup: "Quads", name: "Offset Front Rack DB Squat", videoUrl: "https://www.youtube.com/watch?v=nxpxTIxAaow" },
  { id: "quads-offset-front-rack-kb-squat", muscleGroup: "Quads", name: "Offset Front Rack KB Squat", videoUrl: "https://youtu.be/FS2frFlodpQ?si=5_GvMCIWKHEAjrBP" },
  { id: "quads-one-leg-leg-extension", muscleGroup: "Quads", name: "One-leg Leg Extension", videoUrl: "https://www.youtube.com/watch?v=BaIjF2G8b4A" },
  { id: "quads-one-leg-leg-press", muscleGroup: "Quads", name: "One-leg Leg Press", videoUrl: "https://www.youtube.com/watch?v=BsOg0iBKs6A" },
  { id: "quads-pistol-squat", muscleGroup: "Quads", name: "Pistol Squat", videoUrl: "https://www.youtube.com/watch?v=8GdvZycQmT4" },
  { id: "quads-rear-foot-elevated-split-squat", muscleGroup: "Quads", name: "Rear Foot Elevated Split Squat", videoUrl: "https://www.youtube.com/watch?v=8kvZmrlOo2M" },
  { id: "quads-reverse-nordic-curl", muscleGroup: "Quads", name: "Reverse Nordic Curl", videoUrl: "https://www.youtube.com/watch?v=x2K8uH7dcqg" },
  { id: "quads-safety-bar-squat", muscleGroup: "Quads", name: "Safety Bar Squat", videoUrl: "https://www.youtube.com/watch?v=Amb9NJu4c4E" },
  { id: "quads-safety-bar-squat-heels-elevated", muscleGroup: "Quads", name: "Safety Bar Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=vGWd2PMA4ok" },
  { id: "quads-safety-bar-squat-to-box", muscleGroup: "Quads", name: "Safety Bar Squat to Box", videoUrl: "https://www.youtube.com/watch?v=RAd4A1WuZtE" },
  { id: "quads-sissy-squat-w-bands", muscleGroup: "Quads", name: "Sissy Squat. w/Bands", videoUrl: "https://youtu.be/_jwAGRmnemI?t=42" },
  { id: "quads-staggered-cable-squat-heel-elevated", muscleGroup: "Quads", name: "Staggered Cable Squat (Heel Elevated)", videoUrl: "https://www.instagram.com/p/CMSlK-YjBCl/" },
  { id: "quads-staggered-goblet-squat", muscleGroup: "Quads", name: "Staggered Goblet Squat", videoUrl: "https://www.youtube.com/watch?v=akOGTTd5CbI" },
  { id: "quads-staggered-squat-to-box", muscleGroup: "Quads", name: "Staggered Squat to Box", videoUrl: "https://www.youtube.com/watch?v=VzkHHJZRhVY" },
  { id: "quads-step-up", muscleGroup: "Quads", name: "Step-up", videoUrl: "https://youtu.be/l4AA5d5mInQ?t=24" },
  { id: "quads-trx-one-arm-pistol-squat", muscleGroup: "Quads", name: "TRX One-Arm Pistol Squat", videoUrl: "https://youtu.be/BEbaYWsPTAw?t=12" },
  { id: "quads-trx-pistol-squat", muscleGroup: "Quads", name: "TRX Pistol Squat", videoUrl: "https://www.youtube.com/watch?v=geu8LnnTrSo" },
  { id: "quads-trx-pistol-squat-arms-straight", muscleGroup: "Quads", name: "TRX Pistol Squat (Arms Straight)", videoUrl: "https://youtu.be/6ATZsRwrTiU?si=z2DkQFB_gfHbdIdT&t=34" },
  { id: "quads-terminal-knee-extension", muscleGroup: "Quads", name: "Terminal Knee Extension", videoUrl: "https://www.youtube.com/watch?v=qwIZuT_2sUU&feature=youtu.be" },
  { id: "quads-trap-bar-squat", muscleGroup: "Quads", name: "Trap Bar Squat", videoUrl: "https://www.youtube.com/watch?v=M-3wmzwsUxc" },
  { id: "quads-trap-bar-squat-heels-elevated", muscleGroup: "Quads", name: "Trap Bar Squat (Heels Elevated)", videoUrl: "https://youtu.be/3HJxxKAB3Jo?t=26" },
  { id: "quads-zercher-foot-elevated-reverse-lunge", muscleGroup: "Quads", name: "Zercher Foot-Elevated Reverse Lunge", videoUrl: "https://www.youtube.com/watch?v=Z8rRMLzE7Zg" },
  { id: "quads-zercher-squat", muscleGroup: "Quads", name: "Zercher Squat", videoUrl: "https://www.youtube.com/watch?v=GBQUDD0qosY" },
  { id: "quads-zercher-squat-heels-elevated", muscleGroup: "Quads", name: "Zercher Squat (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=9hTzOCBIuF8" },
  { id: "quads-zercher-squat-to-box", muscleGroup: "Quads", name: "Zercher Squat to Box", videoUrl: "https://www.youtube.com/watch?v=7J8VeUdUdbU" },
  { id: "quads-zercher-squat-to-box-heels-elevated", muscleGroup: "Quads", name: "Zercher Squat to Box (Heels Elevated)", videoUrl: "https://www.youtube.com/watch?v=uBrvVsZWsZ8" },
  { id: "hamstrings-45-degree-hip-extension", muscleGroup: "Hamstrings", name: "45 Degree Hip Extension", videoUrl: "https://www.youtube.com/watch?v=wmB_AETn1fs" },
  { id: "hamstrings-cable-romanian-deadlift-dual-cable", muscleGroup: "Hamstrings", name: "Cable Romanian Deadlift (Dual Cable)", videoUrl: "https://www.youtube.com/watch?v=8YSRjsClDhY" },
  { id: "hamstrings-cable-romanian-deadlift-straight-bar", muscleGroup: "Hamstrings", name: "Cable Romanian Deadlift (Straight Bar)", videoUrl: "https://www.youtube.com/watch?v=OCtb5fsb-Bo" },
  { id: "hamstrings-camporini-deadlift-toe-elevated", muscleGroup: "Hamstrings", name: "Camporini Deadlift (Toe Elevated)", videoUrl: "https://www.youtube.com/watch?v=cTXuf1uR53M" },
  { id: "hamstrings-camporini-deadlift-heel-elevated", muscleGroup: "Hamstrings", name: "Camporini Deadlift(Heel Elevated)", videoUrl: "https://www.youtube.com/watch?v=f4xabfOKd5Y" },
  { id: "hamstrings-db-romanian-deadlift", muscleGroup: "Hamstrings", name: "DB Romanian Deadlift", videoUrl: "https://youtu.be/tH0stBpF7ko?t=9" },
  { id: "hamstrings-db-romanian-deadlift-butt-to-wall", muscleGroup: "Hamstrings", name: "DB Romanian Deadlift (Butt-to-wall)", videoUrl: "https://youtu.be/CIMOWmr4WvM?si=uw_n_8MoRptSR575&t=129" },
  { id: "hamstrings-db-romanian-deadlift-heels-elevated", muscleGroup: "Hamstrings", name: "DB Romanian Deadlift (Heels Elevated)", videoUrl: "https://youtu.be/BuU4ek9B534" },
  { id: "hamstrings-db-romanian-deadlift-toes-elevated", muscleGroup: "Hamstrings", name: "DB Romanian Deadlift (Toes Elevated)", videoUrl: "https://www.youtube.com/watch?v=5vu4oytOYjw" },
  { id: "hamstrings-feet-elevated-glute-iso-bridge-heel", muscleGroup: "Hamstrings", name: "Feet Elevated Glute Iso Bridge (Heel)", videoUrl: "https://www.youtube.com/watch?v=J0kFgnhle6w" },
  { id: "hamstrings-foam-roller-wall-supported-deadlift", muscleGroup: "Hamstrings", name: "Foam Roller Wall-Supported Deadlift", videoUrl: "https://www.youtube.com/shorts/0Bond2NAOro" },
  { id: "hamstrings-gliding-leg-curl", muscleGroup: "Hamstrings", name: "Gliding Leg Curl", videoUrl: "https://www.youtube.com/watch?v=3x6GaEY13yY" },
  { id: "hamstrings-glute-ham-raise", muscleGroup: "Hamstrings", name: "Glute-ham Raise", videoUrl: "https://www.youtube.com/watch?v=ueqa8MPH9bk" },
  { id: "hamstrings-good-mornings", muscleGroup: "Hamstrings", name: "Good Mornings", videoUrl: "https://www.youtube.com/watch?v=dEJ0FTm-CEk" },
  { id: "hamstrings-kb-clean", muscleGroup: "Hamstrings", name: "KB Clean", videoUrl: "https://youtu.be/6AIlgwod8cY?si=hsWD-qtsaT38KF2D&t=14" },
  { id: "hamstrings-kb-deadlift", muscleGroup: "Hamstrings", name: "KB Deadlift", videoUrl: "https://youtu.be/_EpZKt7NjgQ?t=1m48s" },
  { id: "hamstrings-kb-sumo-deadlift-to-box", muscleGroup: "Hamstrings", name: "KB Sumo Deadlift to Box", videoUrl: "https://www.youtube.com/shorts/ZXK4pjv8s5k" },
  { id: "hamstrings-kb-swing", muscleGroup: "Hamstrings", name: "KB Swing", videoUrl: "https://youtu.be/3-MGwX-mPro?t=40s" },
  { id: "hamstrings-lying-cable-leg-curl", muscleGroup: "Hamstrings", name: "Lying Cable Leg Curl", videoUrl: "https://youtu.be/WN5KD33ks2g?si=ETUKP3xpRDCve0Zk&t=38" },
  { id: "hamstrings-lying-leg-curl", muscleGroup: "Hamstrings", name: "Lying Leg Curl", videoUrl: "https://youtu.be/1Tq3QdYUuHs?t=58s" },
  { id: "hamstrings-nordic-hams-with-push-up-assistance", muscleGroup: "Hamstrings", name: "Nordic Hams (with push-up assistance)", videoUrl: "https://www.youtube.com/watch?v=pVbaI2Wi9Jo" },
  { id: "hamstrings-nordic-hamstring-curl", muscleGroup: "Hamstrings", name: "Nordic Hamstring Curl", videoUrl: "https://youtu.be/etmzaHdMaeY?t=1m13s" },
  { id: "hamstrings-one-leg-cable-romanian-deadlift-contr", muscleGroup: "Hamstrings", name: "One-Leg Cable Romanian Deadlift (Contr)", videoUrl: "https://www.youtube.com/shorts/CSF4WQlO-dU" },
  { id: "hamstrings-one-leg-cable-romanian-deadlift-straight-bar", muscleGroup: "Hamstrings", name: "One-Leg Cable Romanian Deadlift (Straight Bar)", videoUrl: "https://www.youtube.com/watch?v=HG_JI6Yzso8" },
  { id: "hamstrings-one-leg-db-romanian-deadlift", muscleGroup: "Hamstrings", name: "One-Leg DB Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=IlOrGu1qzWs" },
  { id: "hamstrings-one-leg-gliding-leg-curl", muscleGroup: "Hamstrings", name: "One-Leg Gliding Leg Curl", videoUrl: "https://youtu.be/PuE1lfMrZr4?si=p29iAozVO1bBJET5&t=16" },
  { id: "hamstrings-one-leg-romanian-deadlift", muscleGroup: "Hamstrings", name: "One-Leg Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=wYG-zRl-VY4" },
  { id: "hamstrings-one-leg-foot-elevated-glute-bridge-heel", muscleGroup: "Hamstrings", name: "One-leg Foot Elevated Glute Bridge (Heel)", videoUrl: "https://youtu.be/Gp_pqzbMSOM?t=91" },
  { id: "hamstrings-one-leg-foot-elevated-glute-iso-bridge-heel", muscleGroup: "Hamstrings", name: "One-leg Foot Elevated Glute Iso Bridge (Heel)", videoUrl: "https://www.youtube.com/watch?v=8A58oebWtMw" },
  { id: "hamstrings-one-leg-lying-cable-leg-curl", muscleGroup: "Hamstrings", name: "One-leg Lying Cable Leg Curl", videoUrl: "https://www.youtube.com/watch?v=s68p3BBU820" },
  { id: "hamstrings-one-leg-lying-leg-curl", muscleGroup: "Hamstrings", name: "One-leg Lying Leg Curl", videoUrl: "https://www.youtube.com/watch?v=aTcoBxhPaHs" },
  { id: "hamstrings-one-leg-seated-leg-curl", muscleGroup: "Hamstrings", name: "One-leg Seated Leg Curl", videoUrl: "https://www.youtube.com/watch?v=SRG3YGPMP1k" },
  { id: "hamstrings-one-leg-straight-leg-hip-extension", muscleGroup: "Hamstrings", name: "One-leg Straight Leg Hip Extension", videoUrl: "https://www.youtube.com/watch?v=mEKOPqG6QTk" },
  { id: "hamstrings-prone-db-leg-curl", muscleGroup: "Hamstrings", name: "Prone DB Leg Curl", videoUrl: "https://www.youtube.com/watch?v=cSzoVHHnuu0" },
  { id: "hamstrings-razor-curl", muscleGroup: "Hamstrings", name: "Razor Curl", videoUrl: "https://youtu.be/baSCjQAvq6g?t=31" },
  { id: "hamstrings-romanian-deadlift", muscleGroup: "Hamstrings", name: "Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=_PWr9C9zTzs" },
  { id: "hamstrings-romanian-deadlift-w-block-squeeze-toes-elevated", muscleGroup: "Hamstrings", name: "Romanian Deadlift w/Block Squeeze (Toes Elevated)", videoUrl: "https://www.youtube.com/watch?v=hRJxvA81tsU" },
  { id: "hamstrings-seated-leg-curl", muscleGroup: "Hamstrings", name: "Seated Leg Curl", videoUrl: "https://www.youtube.com/watch?v=CcQzmFsyVnQ" },
  { id: "hamstrings-sliding-leg-curl", muscleGroup: "Hamstrings", name: "Sliding Leg Curl", videoUrl: "https://youtu.be/RmsTFCQ3Qig?t=12" },
  { id: "hamstrings-smith-machine-romanian-deadlift", muscleGroup: "Hamstrings", name: "Smith Machine Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=G6saqfkdBFQ" },
  { id: "hamstrings-snatch-grip-romanian-deadlift", muscleGroup: "Hamstrings", name: "Snatch-grip Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=tGFRT0Jda6Y" },
  { id: "hamstrings-split-stance-db-romanian-deadlift", muscleGroup: "Hamstrings", name: "Split Stance DB Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=LBzxZCUZrNA" },
  { id: "hamstrings-split-stance-romanian-deadlift", muscleGroup: "Hamstrings", name: "Split Stance Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=HnbW9zcKDT4" },
  { id: "hamstrings-split-stance-trap-bar-romanian-deadlift", muscleGroup: "Hamstrings", name: "Split Stance Trap Bar Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=mmgVxZRLKfM" },
  { id: "hamstrings-standing-leg-curl", muscleGroup: "Hamstrings", name: "Standing Leg Curl", videoUrl: "https://youtu.be/Z053-kKjesQ?t=1m" },
  { id: "hamstrings-standing-one-leg-cable-hamstring-curl", muscleGroup: "Hamstrings", name: "Standing One-Leg Cable Hamstring Curl", videoUrl: "https://www.youtube.com/watch?v=OA7c_8HfdOw" },
  { id: "hamstrings-straight-leg-lying-hip-extension", muscleGroup: "Hamstrings", name: "Straight Leg Lying Hip Extension", videoUrl: "https://www.youtube.com/watch?v=CMQzFSVkJVc&app=desktop" },
  { id: "hamstrings-sumo-deadlift", muscleGroup: "Hamstrings", name: "Sumo Deadlift", videoUrl: "https://youtu.be/PQ3A_HmfQyk?t=28s" },
  { id: "hamstrings-suspended-leg-curl", muscleGroup: "Hamstrings", name: "Suspended Leg Curl", videoUrl: "https://youtu.be/kIpCwuPbL8s?t=4" },
  { id: "hamstrings-suspended-leg-curl-feet-elevated", muscleGroup: "Hamstrings", name: "Suspended Leg Curl (Feet Elevated)", videoUrl: "https://www.youtube.com/watch?v=Jdf9HlWDfjM" },
  { id: "hamstrings-suspended-leg-curl-hips-extended", muscleGroup: "Hamstrings", name: "Suspended Leg Curl (Hips Extended)", videoUrl: "https://exrx.net/WeightExercises/Hamstrings/STStraightHipLegCurl" },
  { id: "hamstrings-swiss-ball-leg-curl", muscleGroup: "Hamstrings", name: "Swiss Ball Leg Curl", videoUrl: "https://youtu.be/czf-1snzG2c?t=22s" },
  { id: "hamstrings-tall-kneeling-hip-hinge", muscleGroup: "Hamstrings", name: "Tall-Kneeling Hip Hinge", videoUrl: "https://www.youtube.com/watch?v=H0XU5Ozl44c" },
  { id: "hamstrings-toes-elevated-ipsilateral-camporini-deadlift", muscleGroup: "Hamstrings", name: "Toes Elevated Ipsilateral Camporini Deadlift", videoUrl: "https://www.youtube.com/watch?v=NJ7k_X5MoXc&list=PLp8XlFjGyKNYegPCZPlDlYKyvxfnihMLq&index=3" },
  { id: "hamstrings-trap-bar-deadlift", muscleGroup: "Hamstrings", name: "Trap Bar Deadlift", videoUrl: "https://youtu.be/tpUKFfIFG24?si=fG0s5NzN1UCe3fJe&t=16" },
  { id: "hamstrings-trap-bar-romanian-deadlift", muscleGroup: "Hamstrings", name: "Trap Bar Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=SKrUfcwEwNA" },
  { id: "hamstrings-treadmill-hamstring-curls", muscleGroup: "Hamstrings", name: "Treadmill Hamstring Curls", videoUrl: "https://youtu.be/C_gM_2rUPvA?t=61" },
  { id: "hamstrings-v-squat-machine-romanian-deadlift", muscleGroup: "Hamstrings", name: "V-Squat Machine Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=mPSepfbZs4o" },
  { id: "hamstrings-wall-supported-db-romanian-deadlift", muscleGroup: "Hamstrings", name: "Wall-Supported DB Romanian Deadlift", videoUrl: "https://www.youtube.com/watch?v=RudZQyXpsHs" },
  { id: "glutes-band-hip-thrust", muscleGroup: "Glutes", name: "Band Hip Thrust", videoUrl: "https://www.youtube.com/watch?v=mHhg59BCa3M&list=PL2vvPjRDHAuSMjjq3sOm1XT6h-pFxcG9c&index=46" },
  { id: "glutes-band-kneeling-hip-thrust", muscleGroup: "Glutes", name: "Band Kneeling Hip Thrust", videoUrl: "https://youtu.be/I3Pgx8Cl9m0?t=29" },
  { id: "glutes-band-pull-through", muscleGroup: "Glutes", name: "Band Pull-Through", videoUrl: "https://youtu.be/HXoox4cLG1U?t=33" },
  { id: "glutes-band-pull-through-w-handle", muscleGroup: "Glutes", name: "Band Pull-Through w/Handle", videoUrl: "https://www.youtube.com/watch?v=WtW1ZjQNWns" },
  { id: "glutes-band-quadruped-hip-extension", muscleGroup: "Glutes", name: "Band Quadruped Hip Extension", videoUrl: "https://youtu.be/E-Df1V-UP7g?t=21" },
  { id: "glutes-band-seated-hip-abduction", muscleGroup: "Glutes", name: "Band Seated Hip Abduction", videoUrl: "https://www.youtube.com/watch?v=uo4_wM5r7zY" },
  { id: "glutes-band-side-lying-clam", muscleGroup: "Glutes", name: "Band Side-lying Clam", videoUrl: "https://youtu.be/fGN7U21c6Js?t=21s" },
  { id: "glutes-band-glute-bridge", muscleGroup: "Glutes", name: "Band glute bridge", videoUrl: "https://youtu.be/dYFxm-oCMDk?t=12s" },
  { id: "glutes-barbell-glute-bridge", muscleGroup: "Glutes", name: "Barbell Glute Bridge", videoUrl: "https://www.youtube.com/watch?v=dyNLdfHaT-U" },
  { id: "glutes-barbell-hip-thrust", muscleGroup: "Glutes", name: "Barbell Hip Thrust", videoUrl: "https://youtu.be/Zp26q4BY5HE?t=18" },
  { id: "glutes-barbell-hip-thrust-w-deficit", muscleGroup: "Glutes", name: "Barbell Hip Thrust w/ Deficit", videoUrl: "https://www.youtube.com/watch?v=ewMYjPREBqc" },
  { id: "glutes-db-hip-thrust", muscleGroup: "Glutes", name: "DB Hip Thrust", videoUrl: "https://youtu.be/Brw7T7sxIPg?t=36" },
  { id: "glutes-db-hip-thrust-w-block-squeeze", muscleGroup: "Glutes", name: "DB Hip Thrust w/Block Squeeze", videoUrl: "https://www.youtube.com/watch?v=OQZzevQ4Qwk" },
  { id: "glutes-double-banded-hip-thrust", muscleGroup: "Glutes", name: "Double Banded Hip Thrust", videoUrl: "https://youtu.be/fouQlVcMVl4?t=65" },
  { id: "glutes-feet-elevated-glute-bridge", muscleGroup: "Glutes", name: "Feet Elevated Glute Bridge", videoUrl: "https://www.youtube.com/watch?v=tgJU9cODIWY" },
  { id: "glutes-foam-roller-bridge", muscleGroup: "Glutes", name: "Foam Roller Bridge", videoUrl: "https://www.youtube.com/watch?v=ZUJVdOEOSRw" },
  { id: "glutes-frog-hip-extension", muscleGroup: "Glutes", name: "Frog Hip Extension", videoUrl: "https://youtu.be/2Mk34bOU79w" },
  { id: "glutes-frog-pump", muscleGroup: "Glutes", name: "Frog Pump", videoUrl: "https://youtu.be/Sx5lE_HlVrA?t=27s" },
  { id: "glutes-glute-bridge", muscleGroup: "Glutes", name: "Glute Bridge", videoUrl: "https://www.youtube.com/watch?v=8bbE64NuDTU" },
  { id: "glutes-glute-bridge-knee-to-chest", muscleGroup: "Glutes", name: "Glute Bridge Knee to Chest", videoUrl: "https://www.youtube.com/watch?v=RaIXSv7LLUA" },
  { id: "glutes-glute-bridge-v-walk-outs", muscleGroup: "Glutes", name: "Glute Bridge V Walk-outs", videoUrl: "https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DXGhWaaUZd7E&data=02%7C01%7C%7Cae52a3c38dd345489ea108d54ac1168c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636497115521910537&sdata=21jIub%2BmQSkcYmssBuq3XBlpDFUGE%2FiMsARQPFbcJN4%3D&reserved=0" },
  { id: "glutes-glute-bridge-walk-outs", muscleGroup: "Glutes", name: "Glute Bridge Walk-outs", videoUrl: "https://www.youtube.com/watch?v=GcV2LB0qqnY" },
  { id: "glutes-glute-bridge-w-block-squeeze", muscleGroup: "Glutes", name: "Glute Bridge w/Block Squeeze", videoUrl: "https://www.youtube.com/watch?v=dN_8taQMEdI" },
  { id: "glutes-glute-max-db-reverse-lunge", muscleGroup: "Glutes", name: "Glute Max DB Reverse Lunge", videoUrl: "https://www.youtube.com/watch?v=buYwR7iRrTM" },
  { id: "glutes-glute-max-wide-arc-cable-kickback", muscleGroup: "Glutes", name: "Glute Max Wide Arc Cable Kickback", videoUrl: "https://www.youtube.com/watch?v=aLw_rQ1zWns" },
  { id: "glutes-glute-rounded-hip-extension", muscleGroup: "Glutes", name: "Glute Rounded Hip Extension", videoUrl: "https://youtu.be/GFqfIInCuUQ?si=a1aG1vBfQY1xZy6_&t=27" },
  { id: "glutes-hip-banded-romanian-deadlift-glute", muscleGroup: "Glutes", name: "Hip-Banded Romanian Deadlift (Glute)", videoUrl: "https://youtu.be/bSYqD-PJGS8?t=29" },
  { id: "glutes-leg-extension-glute-kickback", muscleGroup: "Glutes", name: "Leg Extension Glute Kickback", videoUrl: "https://www.youtube.com/watch?v=3bVH5wW1o2Y" },
  { id: "glutes-leg-press-glute-dominant", muscleGroup: "Glutes", name: "Leg Press (Glute Dominant)", videoUrl: "https://youtu.be/2WzJbFY__lk?t=130" },
  { id: "glutes-machine-hip-thrust", muscleGroup: "Glutes", name: "Machine Hip Thrust", videoUrl: "https://www.youtube.com/watch?v=ZSPmIyX9RZs" },
  { id: "glutes-machine-weighted-step-down-glute", muscleGroup: "Glutes", name: "Machine Weighted Step-down (Glute)", videoUrl: "https://youtu.be/n6CAljTYYvg" },
  { id: "glutes-off-bench-side-lying-hip-abduction", muscleGroup: "Glutes", name: "Off-bench Side-lying Hip Abduction", videoUrl: "https://www.youtube.com/watch?v=kfbS8bJmnN0" },
  { id: "glutes-one-leg-foam-roller-bridge", muscleGroup: "Glutes", name: "One-Leg Foam Roller Bridge", videoUrl: "https://www.youtube.com/shorts/-fbvykiOawQ" },
  { id: "glutes-one-leg-foot-elevated-glute-bridge", muscleGroup: "Glutes", name: "One-leg Foot Elevated Glute Bridge", videoUrl: "https://www.youtube.com/watch?v=zI0yglubLpE" },
  { id: "glutes-one-leg-glute-bridge", muscleGroup: "Glutes", name: "One-leg Glute Bridge", videoUrl: "https://youtu.be/3NXv0Nany-Q?t=4" },
  { id: "glutes-one-leg-hip-thrust", muscleGroup: "Glutes", name: "One-leg Hip Thrust", videoUrl: "https://www.youtube.com/watch?v=BMIy2gtjsTI" },
  { id: "glutes-one-leg-hip-thrust-bw", muscleGroup: "Glutes", name: "One-leg Hip Thrust (BW)", videoUrl: "https://www.youtube.com/watch?v=DnOD1cPFVdM" },
  { id: "glutes-one-leg-hip-thrust-with-deficit", muscleGroup: "Glutes", name: "One-leg Hip Thrust with Deficit", videoUrl: "https://youtu.be/oGBAMIUPTHo?t=7" },
  { id: "glutes-pull-through", muscleGroup: "Glutes", name: "Pull-through", videoUrl: "https://www.youtube.com/watch?v=1cLH4xKji5c" },
  { id: "glutes-seated-hip-abduction", muscleGroup: "Glutes", name: "Seated Hip Abduction", videoUrl: "https://youtu.be/70sMd722ymU?t=4s" },
  { id: "glutes-standing-cable-hip-abduction", muscleGroup: "Glutes", name: "Standing Cable Hip Abduction", videoUrl: "https://www.youtube.com/watch?v=vSqhrbzZb7A" },
  { id: "glutes-standing-cable-hip-abduction-45-deg", muscleGroup: "Glutes", name: "Standing Cable Hip Abduction (45 deg)", videoUrl: "https://youtu.be/wkkZfPrEU40?t=44" },
  { id: "glutes-standing-loaded-hip-abduction", muscleGroup: "Glutes", name: "Standing Loaded Hip Abduction", videoUrl: "https://www.youtube.com/watch?v=Az2cxUMYKK8" },
  { id: "glutes-walking-lunge-contr-rotation", muscleGroup: "Glutes", name: "Walking Lunge (Contr Rotation)", videoUrl: "https://www.youtube.com/watch?v=QfPfKWAzsb4" },
  { id: "glutes-weighted-clam-shells", muscleGroup: "Glutes", name: "Weighted Clam Shells", videoUrl: "https://www.youtube.com/watch?v=sy8KpoY_OU8" },
  { id: "glutes-weighted-donkey-kick-machine", muscleGroup: "Glutes", name: "Weighted Donkey Kick (Machine)", videoUrl: "https://www.youtube.com/watch?v=OkWvPSzUt0Q" },
  { id: "calves-barbell-standing-calf-raise-against-the-rack", muscleGroup: "Calves", name: "Barbell Standing Calf Raise against the rack", videoUrl: "https://www.exrx.net/WeightExercises/Gastrocnemius/BBStandingCalfRaise" },
  { id: "calves-cable-calf-raise", muscleGroup: "Calves", name: "Cable Calf Raise", videoUrl: "https://www.youtube.com/watch?v=Kx5fAImDxeQ" },
  { id: "calves-calf-jump", muscleGroup: "Calves", name: "Calf Jump", videoUrl: "https://www.youtube.com/watch?v=-3UX_nUp4fU" },
  { id: "calves-db-seated-calf-raise", muscleGroup: "Calves", name: "DB Seated Calf Raise", videoUrl: "https://youtu.be/ldpodfZ7LWY?t=22" },
  { id: "calves-leg-curl-seated-calf-raise", muscleGroup: "Calves", name: "Leg Curl Seated Calf Raise", videoUrl: "https://www.youtube.com/shorts/tlECTzekxoM" },
  { id: "calves-leg-press-calf-jump", muscleGroup: "Calves", name: "Leg Press Calf Jump", videoUrl: "https://www.youtube.com/watch?v=yWFtcN9tvfA" },
  { id: "calves-leg-press-calf-raise", muscleGroup: "Calves", name: "Leg Press Calf Raise", videoUrl: "https://www.youtube.com/watch?v=zNH-hbSsH6k" },
  { id: "calves-one-leg-bodyweight-calf-raise", muscleGroup: "Calves", name: "One-Leg Bodyweight Calf Raise", videoUrl: "https://www.youtube.com/watch?v=Tla2ScHQgu0" },
  { id: "calves-one-leg-leg-extension-seated-calf-raise", muscleGroup: "Calves", name: "One-Leg Leg Extension Seated Calf Raise", videoUrl: "https://www.youtube.com/watch?v=kivABH6ohOg" },
  { id: "calves-one-leg-seated-calf-raise", muscleGroup: "Calves", name: "One-Leg Seated Calf Raise", videoUrl: "https://www.youtube.com/watch?v=4NUJeFJ14F4" },
  { id: "calves-one-leg-bent-knee-calf-raise", muscleGroup: "Calves", name: "One-leg Bent Knee Calf Raise", videoUrl: "https://www.youtube.com/watch?v=jXFP4M5B7o0" },
  { id: "calves-one-leg-calf-raise", muscleGroup: "Calves", name: "One-leg Calf Raise", videoUrl: "https://www.youtube.com/watch?v=8XQSbQSvH2M" },
  { id: "calves-seated-calf-raise", muscleGroup: "Calves", name: "Seated Calf Raise", videoUrl: "https://youtu.be/JbyjNymZOt0?t=18s" },
  { id: "calves-smith-machine-calf-raise", muscleGroup: "Calves", name: "Smith Machine Calf Raise", videoUrl: "https://www.youtube.com/watch?v=1lKjFPrYqf0" },
  { id: "calves-smith-machine-seated-calf-raise", muscleGroup: "Calves", name: "Smith Machine Seated Calf Raise", videoUrl: "https://youtu.be/kxzr_bPqgoU?t=164" },
  { id: "calves-standing-calf-raise", muscleGroup: "Calves", name: "Standing Calf Raise", videoUrl: "https://www.youtube.com/watch?v=mucRuC4sEjQ&feature=youtu.be" },
  { id: "calves-standing-calf-raise-machine", muscleGroup: "Calves", name: "Standing Calf Raise Machine", videoUrl: "https://youtu.be/YMmgqO8Jo-k?t=1m26s" },
  { id: "calves-standing-db-calf-raise", muscleGroup: "Calves", name: "Standing DB Calf Raise", videoUrl: "https://youtu.be/HvvqTpTongY" },
  { id: "core-aeiral-hoop-skin-the-cat", muscleGroup: "Core", name: "Aeiral Hoop Skin-The-Cat", videoUrl: "https://www.youtube.com/shorts/MtGJ9nmTa7c" },
  { id: "core-alternating-superman", muscleGroup: "Core", name: "Alternating Superman", videoUrl: "https://www.youtube.com/watch?v=Z4WNSmm19wk" },
  { id: "core-bear-knee-taps", muscleGroup: "Core", name: "Bear Knee Taps", videoUrl: "https://www.youtube.com/watch?v=RMcXZfeBdAo" },
  { id: "core-bird-dog-slide", muscleGroup: "Core", name: "Bird Dog Slide", videoUrl: "https://www.youtube.com/watch?v=QtbtV_7mk_k" },
  { id: "core-copenhagen-side-plank", muscleGroup: "Core", name: "Copenhagen Side Plank", videoUrl: "https://www.youtube.com/watch?v=CjinhqRzcaY" },
  { id: "core-decline-weighted-ab-crunch", muscleGroup: "Core", name: "Decline Weighted Ab Crunch", videoUrl: "https://youtu.be/NwhZZMimiFU?t=10s" },
  { id: "core-diamond-mountain-climber-feet-on-wall", muscleGroup: "Core", name: "Diamond Mountain Climber (Feet on Wall)", videoUrl: "https://www.youtube.com/watch?v=cIwg34EB1kY" },
  { id: "core-farmer-s-walk-w-fat-gripz", muscleGroup: "Core", name: "Farmer's Walk w/ Fat Gripz", videoUrl: "https://www.youtube.com/watch?v=_Ukjwsit5xY" },
  { id: "core-hang-hollow-body", muscleGroup: "Core", name: "Hang (Hollow Body)", videoUrl: "https://youtu.be/TIT4m-BQqTY?si=l9Bq_ZEIWIwa3Ly3" },
  { id: "core-hanging-ab-raise", muscleGroup: "Core", name: "Hanging Ab Raise", videoUrl: "https://youtu.be/DjRtlkH1MSo" },
  { id: "core-hanging-knee-raise", muscleGroup: "Core", name: "Hanging Knee Raise", videoUrl: "https://youtu.be/QyVq5oUBpss?t=1m24s" },
  { id: "core-hollow-body", muscleGroup: "Core", name: "Hollow Body", videoUrl: "https://youtu.be/LlDNef_Ztsc" },
  { id: "core-kneeling-cable-crunch", muscleGroup: "Core", name: "Kneeling Cable Crunch", videoUrl: "https://youtu.be/3qjoXDTuyOE?t=21s" },
  { id: "core-landmine-oblique-twist", muscleGroup: "Core", name: "Landmine Oblique Twist", videoUrl: "https://www.youtube.com/watch?v=4dGj7rES9pY" },
  { id: "core-lateral-lunge-cable-lift", muscleGroup: "Core", name: "Lateral Lunge Cable Lift", videoUrl: "https://youtu.be/kBeqH-rHQrI?si=lExMdfYsK-9uFgNi" },
  { id: "core-machine-crunch", muscleGroup: "Core", name: "Machine Crunch", videoUrl: "https://youtu.be/_O1xunCfYEM?t=50s" },
  { id: "core-plank-w-reach-under", muscleGroup: "Core", name: "Plank w/Reach Under", videoUrl: "https://youtu.be/96FoNFUfPBk?si=b0DaHSuu5ySvW6lV&t=13" },
  { id: "core-rkc-plank", muscleGroup: "Core", name: "RKC plank", videoUrl: "https://www.youtube.com/watch?v=6TKktamzq4o" },
  { id: "core-reverse-crunch", muscleGroup: "Core", name: "Reverse Crunch", videoUrl: "https://www.youtube.com/watch?v=voLIjlsWNPQ" },
  { id: "core-rolling-plank", muscleGroup: "Core", name: "Rolling Plank", videoUrl: "https://youtu.be/FiQjPLTVjb4" },
  { id: "core-seated-cable-crunch", muscleGroup: "Core", name: "Seated Cable Crunch", videoUrl: null },
  { id: "core-side-plank", muscleGroup: "Core", name: "Side Plank", videoUrl: "https://www.youtube.com/watch?v=5YY2pMQNmBk" },
  { id: "core-side-plank-elbow-to-knee", muscleGroup: "Core", name: "Side Plank Elbow to Knee", videoUrl: "https://youtu.be/qqhh1gZF7uA?t=21" },
  { id: "core-side-plank-kneeling", muscleGroup: "Core", name: "Side Plank Kneeling", videoUrl: "https://www.youtube.com/watch?v=UurF0EhHFLg" },
  { id: "core-skin-the-cat", muscleGroup: "Core", name: "Skin-The-Cat", videoUrl: "https://youtu.be/on6KcgkdWaA" },
  { id: "core-split-stance-cable-chop-high-to-low", muscleGroup: "Core", name: "Split Stance Cable Chop (High-to-Low)", videoUrl: "https://www.youtube.com/watch?v=7YDFxkV637c" },
  { id: "core-split-stance-cable-lift", muscleGroup: "Core", name: "Split Stance Cable Lift", videoUrl: "https://www.youtube.com/watch?v=ur3G94bllNo" },
  { id: "core-staggered-stance-facing-cable-chop", muscleGroup: "Core", name: "Staggered Stance Facing Cable Chop", videoUrl: "https://www.youtube.com/shorts/so3zf5jfUpU" },
  { id: "core-standing-pallof-press", muscleGroup: "Core", name: "Standing Pallof Press", videoUrl: "https://youtube.com/shorts/-icUnCb-uAU?feature=share" },
  { id: "core-starfish-crunch", muscleGroup: "Core", name: "Starfish Crunch", videoUrl: "https://youtu.be/HBB5tf2vndA?t=2" },
  { id: "core-superman", muscleGroup: "Core", name: "Superman", videoUrl: "https://www.youtube.com/watch?v=z6PJMT2y8GQ" },
  { id: "core-supinated-plank", muscleGroup: "Core", name: "Supinated Plank", videoUrl: "https://www.youtube.com/watch?v=b26aWcCqOxs" },
  { id: "core-swiss-ball-cable-crunch", muscleGroup: "Core", name: "Swiss Ball Cable Crunch", videoUrl: "https://www.youtube.com/watch?v=O7Rc7v-UxQ4" },
  { id: "core-swiss-ball-crunch", muscleGroup: "Core", name: "Swiss Ball Crunch", videoUrl: "https://youtu.be/VVBddP5oW8Y" },
  { id: "core-wide-stance-anti-rotation-chop", muscleGroup: "Core", name: "Wide-Stance Anti-Rotation Chop", videoUrl: "https://www.youtube.com/watch?v=dwdeKRZ3E6s" },
];
